AddUserReplyErrorCode:
    type: enum
    config:
        name: AddUserReplyErrorCode
        description: 'Available errors for an `addUserReply` mutation.'
        values:
            REQUIREMENTS_NOT_MET:
                value: !php/const Capco\AppBundle\GraphQL\Mutation\AddUserReplyMutation::REQUIREMENTS_NOT_MET
                description: 'the viewer does not meet requirements'
