ArgumentValue:
    type: enum
    config:
        description: 'Value of an argument'
        values:
            AGAINST:
                value: !php/const Capco\AppBundle\Entity\Argument::TYPE_AGAINST
                description: 'AGAINST argument'
            FOR:
                value: !php/const Capco\AppBundle\Entity\Argument::TYPE_FOR
                description: 'FOR argument'
