AvailableSso:
    type: enum
    config:
        description: 'Type of sso service'
        values:
            FRANCE_CONNECT:
                value: !php/const Capco\AppBundle\Enum\AvailableSso::FRANCE_CONNECT
                description: 'FranceConnect sso service'
            FACEBOOK:
                value: !php/const Capco\AppBundle\Enum\AvailableSso::FACEBOOK
                description: 'Facebook sso service'
