AvailableProposalCategoryIcon:
    type: enum
    config:
        description: 'The possible values for a proposal category icon'
        values:
            GAS_STATION:
                value: !php/const Capco\AppBundle\Enum\AvailableProposalCategoryIcon::GAS_STATION
            BOAT:
                value: !php/const Capco\AppBundle\Enum\AvailableProposalCategoryIcon::BOAT
            EARTH:
                value: !php/const Capco\AppBundle\Enum\AvailableProposalCategoryIcon::EARTH
            TRAVEL:
                value: !php/const Capco\AppBundle\Enum\AvailableProposalCategoryIcon::TRAVEL
            PASSPORT:
                value: !php/const Capco\AppBundle\Enum\AvailableProposalCategoryIcon::PASSPORT
            ECONOMY:
                value: !php/const Capco\AppBundle\Enum\AvailableProposalCategoryIcon::ECONOMY
            PARKING:
                value: !php/const Capco\AppBundle\Enum\AvailableProposalCategoryIcon::PARKING
            COCKTAIL:
                value: !php/const Capco\AppBundle\Enum\AvailableProposalCategoryIcon::COCKTAIL
            RESTAURANT:
                value: !php/const Capco\AppBundle\Enum\AvailableProposalCategoryIcon::RESTAURANT
            FARMER_MARKET:
                value: !php/const Capco\AppBundle\Enum\AvailableProposalCategoryIcon::FARMER_MARKET
            NETWORK:
                value: !php/const Capco\AppBundle\Enum\AvailableProposalCategoryIcon::NETWORK
            MOBILE_PHONE:
                value: !php/const Capco\AppBundle\Enum\AvailableProposalCategoryIcon::MOBILE_PHONE
            COMPANY:
                value: !php/const Capco\AppBundle\Enum\AvailableProposalCategoryIcon::COMPANY
            URBANISM:
                value: !php/const Capco\AppBundle\Enum\AvailableProposalCategoryIcon::URBANISM
            VILLAGE:
                value: !php/const Capco\AppBundle\Enum\AvailableProposalCategoryIcon::VILLAGE
            CONSTRUCTION_CONE:
                value: !php/const Capco\AppBundle\Enum\AvailableProposalCategoryIcon::CONSTRUCTION_CONE
            VEGETABLES_PLATE:
                value: !php/const Capco\AppBundle\Enum\AvailableProposalCategoryIcon::VEGETABLES_PLATE
            GROCERY_SHOPPING:
                value: !php/const Capco\AppBundle\Enum\AvailableProposalCategoryIcon::GROCERY_SHOPPING
            SHOPPING_BAG:
                value: !php/const Capco\AppBundle\Enum\AvailableProposalCategoryIcon::SHOPPING_BAG
            MEDICAL:
                value: !php/const Capco\AppBundle\Enum\AvailableProposalCategoryIcon::MEDICAL
            HOSPITAL:
                value: !php/const Capco\AppBundle\Enum\AvailableProposalCategoryIcon::HOSPITAL
            HEALTH:
                value: !php/const Capco\AppBundle\Enum\AvailableProposalCategoryIcon::HEALTH
            BICYCLE:
                value: !php/const Capco\AppBundle\Enum\AvailableProposalCategoryIcon::BICYCLE
            OFFICER:
                value: !php/const Capco\AppBundle\Enum\AvailableProposalCategoryIcon::OFFICER
            SURVEILLANCE_CAMERA:
                value: !php/const Capco\AppBundle\Enum\AvailableProposalCategoryIcon::SURVEILLANCE_CAMERA
            FAMILY_CHILDREN:
                value: !php/const Capco\AppBundle\Enum\AvailableProposalCategoryIcon::FAMILY_CHILDREN
            FAMILY_WALK_PARK:
                value: !php/const Capco\AppBundle\Enum\AvailableProposalCategoryIcon::FAMILY_WALK_PARK
            FAMILY_CHILD_PLAY_BALL:
                value: !php/const Capco\AppBundle\Enum\AvailableProposalCategoryIcon::FAMILY_CHILD_PLAY_BALL
            BASKETBALL_BALL:
                value: !php/const Capco\AppBundle\Enum\AvailableProposalCategoryIcon::BASKETBALL_BALL
            DOG_LEASH:
                value: !php/const Capco\AppBundle\Enum\AvailableProposalCategoryIcon::DOG_LEASH
            WATER:
                value: !php/const Capco\AppBundle\Enum\AvailableProposalCategoryIcon::WATER
            TREE:
                value: !php/const Capco\AppBundle\Enum\AvailableProposalCategoryIcon::TREE
            PARK_BENCH_LIGHT:
                value: !php/const Capco\AppBundle\Enum\AvailableProposalCategoryIcon::PARK_BENCH_LIGHT
            RECYCLE:
                value: !php/const Capco\AppBundle\Enum\AvailableProposalCategoryIcon::RECYCLE
            BIN:
                value: !php/const Capco\AppBundle\Enum\AvailableProposalCategoryIcon::BIN
            AGRICULTURE_MACHINE_TRACTOR:
                value: !php/const Capco\AppBundle\Enum\AvailableProposalCategoryIcon::AGRICULTURE_MACHINE_TRACTOR
            HAND:
                value: !php/const Capco\AppBundle\Enum\AvailableProposalCategoryIcon::HAND
            SOLIDARITY:
                value: !php/const Capco\AppBundle\Enum\AvailableProposalCategoryIcon::SOLIDARITY
            HIERARCHY:
                value: !php/const Capco\AppBundle\Enum\AvailableProposalCategoryIcon::HIERARCHY
            ELDERLY:
                value: !php/const Capco\AppBundle\Enum\AvailableProposalCategoryIcon::ELDERLY
            PARAPLEGIC:
                value: !php/const Capco\AppBundle\Enum\AvailableProposalCategoryIcon::PARAPLEGIC
            CAR:
                value: !php/const Capco\AppBundle\Enum\AvailableProposalCategoryIcon::CAR
            CARPOOLING:
                value: !php/const Capco\AppBundle\Enum\AvailableProposalCategoryIcon::CARPOOLING
            BUS_STATION:
                value: !php/const Capco\AppBundle\Enum\AvailableProposalCategoryIcon::BUS_STATION
            RAILROAD_TRAIN:
                value: !php/const Capco\AppBundle\Enum\AvailableProposalCategoryIcon::RAILROAD_TRAIN
            BRIEFCASE:
                value: !php/const Capco\AppBundle\Enum\AvailableProposalCategoryIcon::BRIEFCASE
            BOOK_FLIP_PAGE:
                value: !php/const Capco\AppBundle\Enum\AvailableProposalCategoryIcon::BOOK_FLIP_PAGE
            CULTURE:
                value: !php/const Capco\AppBundle\Enum\AvailableProposalCategoryIcon::CULTURE
            OFFICIAL_BUILDING:
                value: !php/const Capco\AppBundle\Enum\AvailableProposalCategoryIcon::OFFICIAL_BUILDING
            GRADUATE:
                value: !php/const Capco\AppBundle\Enum\AvailableProposalCategoryIcon::GRADUATE
            LIGHT_BULB:
                value: !php/const Capco\AppBundle\Enum\AvailableProposalCategoryIcon::LIGHT_BULB
            ENERGY:
                value: !php/const Capco\AppBundle\Enum\AvailableProposalCategoryIcon::ENERGY
            ICN:
                value: !php/const Capco\AppBundle\Enum\AvailableProposalCategoryIcon::ICN
            ECOLOGY_LEAF:
                value: !php/const Capco\AppBundle\Enum\AvailableProposalCategoryIcon::ECOLOGY_LEAF
