CategoryOrderField:
    type: enum
    config:
        description: 'Ordering options for categories returned from the connection.'
        values:
            ALPHABETICAL:
                value: !php/const Capco\AppBundle\Enum\CategoryOrderField::ALPHABETICAL
                description: 'Allows ordering a list of categories in an alphabetical order.'
