CheckIdentificationCodeErrorCode:
    type: enum
    config:
        name: CheckIdentificationCodeErrorCode
        description: 'Available errors for an `checkIdentificationCode` mutation.'
        values:
            BAD_CODE:
                value: !php/const Capco\AppBundle\Validator\Constraints\CheckIdentificationCode::BAD_CODE
                description: 'The validation code is not valid'
            CODE_ALREADY_USED:
                value: !php/const Capco\AppBundle\Validator\Constraints\CheckIdentificationCode::CODE_ALREADY_USED
                description: 'The validation code is already used'
            VIEWER_ALREADY_HAS_A_CODE:
                value: !php/const Capco\AppBundle\GraphQL\Mutation\CheckIdentificationCodeMutation::VIEWER_ALREADY_HAS_A_CODE
                description: 'The viewer already has an identification code'
            LIMIT_REACHED:
                value: !php/const Capco\AppBundle\Enum\UpdateUserEmailErrorCode::RATE_LIMIT_REACHED
                description: 'The viewer reached the limit to try enter an identification code'
