CivicIASentiment:
    type: enum
    config:
        description: 'Sentiments detected by civicIA.'
        values:
            POSITIVE:
                value: !php/const Capco\AppBundle\Enum\CivicIASentimentEnum::POSITIVE
                description: 'Positive sentiment.'
            NEUTRAL:
                value: !php/const Capco\AppBundle\Enum\CivicIASentimentEnum::NEUTRAL
                description: 'Neutral or undetected sentiment.'
            NEGATIVE:
                value: !php/const Capco\AppBundle\Enum\CivicIASentimentEnum::NEGATIVE
                description: 'Negative sentiment.'
            MIXED:
                value: !php/const Capco\AppBundle\Enum\CivicIASentimentEnum::MIXED
                description: 'Positive and negative sentiment.'
