CommentPublicationStatus:
    type: enum
    config:
        description: 'Available statuses'
        values:
            UNPUBLISHED:
                value: !php/const Capco\AppBundle\Enum\CommentPublicationStatus::UNPUBLISHED
                description: 'Visible by author only.'
            PUBLISHED:
                value: !php/const Capco\AppBundle\Enum\CommentPublicationStatus::PUBLISHED
                description: 'Normal status, Publicly visible'
            TRASHED:
                value: !php/const Capco\AppBundle\Enum\CommentPublicationStatus::TRASHED
                description: 'Publicly visible in the trash bin'
            TRASHED_NOT_VISIBLE:
                value: !php/const Capco\AppBundle\Enum\CommentPublicationStatus::TRASHED_NOT_VISIBLE
                description: 'In the trash bin, content not visible'
