ConcreteStepType:
    type: enum
    config:
        description: 'The different available types of step.'
        values:
            COLLECT:
                value: !php/const Capco\AppBundle\Entity\Steps\CollectStep::TYPE
                description: 'Represent a collect step.'
            SELECTION:
                value: !php/const Capco\AppBundle\Entity\Steps\SelectionStep::TYPE
                description: 'Represent a selection step.'
            CONSULTATION:
                value: !php/const Capco\AppBundle\Entity\Steps\ConsultationStep::TYPE
                description: 'Represent a consultation step.'
            OTHER:
                value: !php/const Capco\AppBundle\Entity\Steps\OtherStep::TYPE
                description: 'Represent a step with no particular behaviour.'
            PRESENTATION:
                value: !php/const Capco\AppBundle\Entity\Steps\PresentationStep::TYPE
                description: 'Represent a presentation step, mainly used to show an introduction.'
            QUESTIONNAIRE:
                value: !php/const Capco\AppBundle\Entity\Steps\QuestionnaireStep::TYPE
                description: 'Represent a questionnaire step.'
            RANKING:
                value: !php/const Capco\AppBundle\Entity\Steps\RankingStep::TYPE
                description: 'Represent a ranking step.'
            DEBATE:
                value: !php/const Capco\AppBundle\Entity\Steps\DebateStep::TYPE
                description: 'Represent a debate step.'
