ContributionType:
    type: enum
    config:
        description: 'Different contribution type'
        values:
            OPINION:
                value: !php/const Capco\AppBundle\Enum\ContributionType::OPINION
                description: 'Get contributions that are an opnion'
            OPINIONVERSION:
                value: !php/const Capco\AppBundle\Enum\ContributionType::OPINIONVERSION
                description: 'Get contributions that are an opnion version'
            COMMENT:
                value: !php/const Capco\AppBundle\Enum\ContributionType::COMMENT
                description: 'Get contributions that are a comment'
            ARGUMENT:
                value: !php/const Capco\AppBundle\Enum\ContributionType::ARGUMENT
                description: 'Get contributions that are an argument'
            SOURCE:
                value: !php/const Capco\AppBundle\Enum\ContributionType::SOURCE
                description: 'Get contributions that are a source'
            PROPOSAL:
                value: !php/const Capco\AppBundle\Enum\ContributionType::PROPOSAL
                description: 'Get contributions that are a proposal'
            REPLY:
                value: !php/const Capco\AppBundle\Enum\ContributionType::REPLY
                description: 'Get contributions that are a reply'
            DEBATEARGUMENT:
                value: !php/const Capco\AppBundle\Enum\ContributionType::DEBATEARGUMENT
                description: 'Get contributions that are debate argument.'
            DEBATEANONYMOUSARGUMENT:
                value: !php/const Capco\AppBundle\Enum\ContributionType::DEBATEANONYMOUSARGUMENT
                description: 'Get contributions that are debate anonymous argument.'
            REPLY_ANONYMOUS:
                value: !php/const Capco\AppBundle\Enum\ContributionType::REPLY_ANONYMOUS
                description: 'Get contributions that are a reply anonymous'
