ContributionOrigin:
    type: enum
    config:
        description: 'The origin of a contribution'
        values:
            INTERNAL:
                value: !php/const Capco\AppBundle\Enum\ContributionOrigin::INTERNAL
                description: 'Created on the platform'
            WIDGET:
                value: !php/const Capco\AppBundle\Enum\ContributionOrigin::WIDGET
                description: 'Created through a widget'
            MAIL:
                value: !php/const Capco\AppBundle\Enum\ContributionOrigin::MAIL
                description: 'Created through email'
