CreateEmailingCampaignErrorCode:
    type: enum
    config:
        name: CreateEmailingCampaignErrorCode
        description: 'Available errors on campaign creation'
        values:
            ID_NOT_FOUND_MAILING_LIST:
                value: !php/const Capco\AppBundle\Enum\CreateEmailingCampaignErrorCode::ID_NOT_FOUND_MAILING_LIST
                description: 'No mailing list match your id'
            ID_NOT_FOUND_GROUP:
                value: !php/const Capco\AppBundle\Enum\CreateEmailingCampaignErrorCode::ID_NOT_FOUND_GROUP
                description: 'No group match your id'
            ID_NOT_FOUND_PROJECT:
                value: !php/const Capco\AppBundle\Enum\CreateEmailingCampaignErrorCode::ID_NOT_FOUND_PROJECT
                description: 'No project match your id'
            DOUBLE_LIST:
                value: !php/const Capco\AppBundle\Enum\UpdateEmailingCampaignErrorCode::DOUBLE_LIST
                description: 'A campaign cannot have both group, project, internal and organic list'
