CreateSenderEmailDomainErrorCode:
    type: enum
    config:
        description: 'Possible errors on createSenderEmailDomain mutation.'
        values:
            ALREADY_EXIST:
                value: !php/const Capco\AppBundle\GraphQL\Mutation\Mailing\CreateSenderEmailDomainMutation::ALREADY_EXIST
                description: 'There is already a SenderEmailDomain matching service and value.'
