CreatePostErrorCode:
    type: enum
    config:
        name: CreatePostErrorCode
        description: 'Available errors on createPost mutation'
        values:
            INVALID_FORM:
                value: !php/const Capco\AppBundle\GraphQL\Mutation\CreatePostMutation::INVALID_FORM
                description: 'Submitted form is invalid'
            INVALID_OWNER:
                value: !php/const Capco\AppBundle\GraphQL\Mutation\CreatePostMutation::INVALID_OWNER
                description: 'Submitted owner is invalid : unknown, different user or organization not belonging.'
