DeleteOfficialResponseErrorCode:
    type: enum
    config:
        name: DeleteOfficialResponseErrorCode
        description: 'Available errors on OfficialResponse removal'
        values:
            ID_NOT_FOUND:
                value: !php/const Capco\AppBundle\Enum\ErrorCode\DeleteOfficialResponseErrorCode::ID_NOT_FOUND
                description: 'No OfficialResponse match your id'
