EmailingCampaignStatus:
    type: enum
    config:
        description: 'The possible status of an emailing campaign'
        values:
            DRAFT:
                value: !php/const Capco\AppBundle\Enum\EmailingCampaignStatus::DRAFT
                description: 'not scheduled'
            SENDING:
                value: !php/const Capco\AppBundle\Enum\EmailingCampaignStatus::SENDING
                description: 'currently sending'
            SENT:
                value: !php/const Capco\AppBundle\Enum\EmailingCampaignStatus::SENT
                description: 'already sent'
            PLANNED:
                value: !php/const Capco\AppBundle\Enum\EmailingCampaignStatus::PLANNED
                description: 'scheduled'
            ARCHIVED:
                value: !php/const Capco\AppBundle\Enum\EmailingCampaignStatus::ARCHIVED
                description: 'archived'
