EmailingCampaignOrderField:
    type: enum
    config:
        description: 'Properties by which campaigns can be ordered'
        values:
            SEND_AT:
                value: !php/const Capco\AppBundle\Enum\EmailingCampaignOrderField::SEND_AT
                description: 'Allows ordering a list of campaign by when they have been sent or shall be sent.'
