EmailingCampaignStatusFilter:
    type: enum
    config:
        description: '3 possible values'
        values:
            DRAFT:
                value: !php/const Capco\AppBundle\Enum\EmailingCampaignStatus::DRAFT
                description: 'campaigns not scheduled'
            SENT:
                value: !php/const Capco\AppBundle\Enum\EmailingCampaignStatus::SENT
                description: 'campaigns already sent'
            PLANNED:
                value: !php/const Capco\AppBundle\Enum\EmailingCampaignStatus::PLANNED
                description: 'campaigns scheduled'
