EventRefusedReason:
    type: enum
    config:
        description: 'Type of refused event reason'
        values:
            SEX:
                value: !php/const Capco\AppBundle\DBAL\Enum\EventReviewRefusedReasonType::SEX
                description: 'The associated event review has been flagged as sexual content'
            OFFENDING:
                value: !php/const Capco\AppBundle\DBAL\Enum\EventReviewRefusedReasonType::OFFENDING
                description: 'The associated event review has been flagged as offending content'
            SPAM:
                value: !php/const Capco\AppBundle\DBAL\Enum\EventReviewRefusedReasonType::SPAM
                description: 'The associated event review has been flagged as spam'
            SYNTAX_ERROR:
                value: !php/const Capco\AppBundle\DBAL\Enum\EventReviewRefusedReasonType::SYNTAX_ERROR
                description: 'The associated event review has been flagged as syntax error'
            WRONG_CONTENT:
                value: !php/const Capco\AppBundle\DBAL\Enum\EventReviewRefusedReasonType::WRONG_CONTENT
                description: 'The associated event review has been flagged as wrong content'
            OFF_TOPIC:
                value: !php/const Capco\AppBundle\DBAL\Enum\EventReviewRefusedReasonType::OFF_TOPIC
                description: 'The associated event review has been flagged as off topic'
            NONE:
                value: !php/const Capco\AppBundle\DBAL\Enum\EventReviewRefusedReasonType::NONE
                description: 'The associated event review has not been flagged'
