FollowerOrderField:
    type: enum
    config:
        description: 'Properties by which follower connections can be ordered'
        values:
            NAME:
                value: !php/const Capco\AppBundle\Enum\FollowerOrderField::NAME
                description: 'Allows ordering a list of followers namely.'
            FOLLOWED_AT:
                value: !php/const Capco\AppBundle\Enum\FollowerOrderField::FOLLOWED_AT
                description: 'Allows ordering a list of followers by when they were followed.'
            RANDOM:
                value: !php/const Capco\AppBundle\Enum\FollowerOrderField::RANDOM
                description: 'Allows ordering a list of followers randomly.'
