ForOrAgainstValue:
    type: enum
    config:
        description: 'For or against.'
        values:
            AGAINST:
                value: !php/const Capco\AppBundle\Enum\ForOrAgainstType::AGAINST
                description: 'An against value'
            FOR:
                value: !php/const Capco\AppBundle\Enum\ForOrAgainstType::FOR
                description: 'A for value'
