FranceConnectAllowedData:
    type: enum
    config:
        description: 'Many possible values'
        values:
            given_name:
                value: !php/const Capco\AppBundle\Enum\FranceConnectAllowedData::GIVEN_NAME
                description: 'Fields firstname'
            family_name:
                value: !php/const Capco\AppBundle\Enum\FranceConnectAllowedData::FAMILY_NAME
                description: 'Fields lastname'
            birthdate:
                value: !php/const Capco\AppBundle\Enum\FranceConnectAllowedData::BIRTHDATE
                description: 'Fields birth date'
            birthplace:
                value: !php/const Capco\AppBundle\Enum\FranceConnectAllowedData::BIRTHPLACE
                description: 'Fields birth place'
            birthcountry:
                value: !php/const Capco\AppBundle\Enum\FranceConnectAllowedData::BIRTHCOUNTRY
                description: 'Fields birth country'
            gender:
                value: !php/const Capco\AppBundle\Enum\FranceConnectAllowedData::GENDER
                description: 'Fields gender'
            email:
                value: !php/const Capco\AppBundle\Enum\FranceConnectAllowedData::EMAIL
                description: 'Fields email'
            preferred_username:
                value: !php/const Capco\AppBundle\Enum\FranceConnectAllowedData::PREFERRED_USERNAME
                description: 'Fields username'
