InternalQuestionnaireAffiliation:
    type: enum
    config:
        name: QuestionnaireAffiliation
        description: 'The affiliation of a user to a questionnaire'
        values:
            OWNER:
                value: !php/const Capco\AppBundle\Enum\QuestionnaireAffiliation::OWNER
                description: 'Questionnaires that are owned by the authenticated user.'
