InternalProposalFormAffiliation:
    type: enum
    config:
        name: ProposalFormAffiliation
        description: 'The affiliation of a user to a `ProposalForm.`'
        values:
            OWNER:
                value: !php/const Capco\AppBundle\Enum\ProposalFormAffiliation::OWNER
                description: '`ProposalForms` that are owned by the authenticated user.'
