InternalSiteSettingsStatus:
    type: enum
    config:
        name: SiteSettingsStatus
        description: 'The status of the domain change.'
        values:
            IDLE:
                value: !php/const Capco\AppBundle\Enum\SiteSettingsStatus::IDLE
                description: 'Custom domain is not set.'
            ACTIVE:
                value: !php/const Capco\AppBundle\Enum\SiteSettingsStatus::ACTIVE
                description: 'The site redirects correctly to the custom domain.'
