InternalContributionOrderField:
    type: enum
    config:
        name: ContributionOrderField
        description: 'Ordering options for contributions connections.'
        values:
            CREATED_AT:
                value: !php/const Capco\AppBundle\Enum\ContributionOrderField::CREATED_AT
                description: 'Allows ordering a list of contributions by when they were created.'
            COMMENT_COUNT:
                value: !php/const Capco\AppBundle\Enum\ContributionOrderField::COMMENT_COUNT
                description: 'Allows ordering a list of contributions by there number of comments.'
            POPULAR:
                value: !php/const Capco\AppBundle\Enum\ContributionOrderField::POPULAR
                description: 'Allows ordering a list of contributions by there number of votes ok.'
            POSITION:
                value: !php/const Capco\AppBundle\Enum\ContributionOrderField::POSITION
                description: 'Allows ordering a list of contributions by there position.'
            PUBLISHED_AT:
                value: !php/const Capco\AppBundle\Enum\ContributionOrderField::PUBLISHED_AT
                description: 'Allows ordering a list of contributions by when they were published.'
            RANDOM:
                value: !php/const Capco\AppBundle\Enum\ContributionOrderField::RANDOM
                description: 'Allows ordering a list of contributions randomly.'
            VOTE_COUNT:
                value: !php/const Capco\AppBundle\Enum\ContributionOrderField::VOTE_COUNT
                description: 'Allows ordering a list of contributions by there number of votes.'
