InternalProposalVoteOrderField:
    type: enum
    config:
        name: ProposalVoteOrderField
        description: 'Ordering options for proposals votes connections.'
        values:
            PUBLISHED_AT:
                value: !php/const Capco\AppBundle\Enum\ProposalOrderField::PUBLISHED_AT
                description: 'Allows ordering a list of vote by when they were published.'
            POSITION:
                value: !php/const Capco\AppBundle\Enum\VoteOrderField::POSITION
                description: 'Allows ordering a list of vote by position.'
