InternalEventAffiliation:
    type: enum
    config:
        name: EventAffiliation
        description: 'The affiliation of a user to a event'
        values:
            OWNER:
                value: !php/const Capco\AppBundle\Enum\EventAffiliation::OWNER
                description: 'Events that are owned by the authenticated user.'
