AddSmsCreditErrorCode:
    type: enum
    config:
        name: AddSmsCreditErrorCode
        description: 'Available errors on addSmsCredit mutation.'
        values:
            ORDER_ALREADY_PROCESSED:
                value: !php/const Capco\AppBundle\GraphQL\Mutation\Sms\AddSmsCreditMutation::ORDER_ALREADY_PROCESSED
                description: 'The given order is already processed.'
            SMS_ORDER_NOT_FOUND:
                value: !php/const Capco\AppBundle\GraphQL\Mutation\Sms\AddSmsCreditMutation::SMS_ORDER_NOT_FOUND
                description: 'The given order is not found.'
            TWILIO_API_ERROR:
                value: !php/const Capco\AppBundle\GraphQL\Mutation\Sms\AddSmsCreditMutation::TWILIO_API_ERROR
                description: 'Error occured while calling twilio API.'
