InternalEventStatus:
    type: enum
    config:
        name: EventStatus
        description: 'List of available filters to filter `Event`'
        values:
            APPROVED:
                value: !php/const Capco\AppBundle\DBAL\Enum\EventReviewStatusType::APPROVED
                description: 'Filter by approved status.'
            AWAITING:
                value: !php/const Capco\AppBundle\DBAL\Enum\EventReviewStatusType::AWAITING
                description: 'Filter by awaiting status.'
            REFUSED:
                value: !php/const Capco\AppBundle\DBAL\Enum\EventReviewStatusType::REFUSED
                description: 'Filter by refused status.'
            DELETED:
                value: !php/const Capco\AppBundle\DBAL\Enum\EventReviewStatusType::DELETED
                description: 'Filter by deleted status.'
