InternalPostAffiliation:
    type: enum
    config:
        name: PostAffiliation
        description: 'The affiliation of a user to a post'
        values:
            OWNER:
                value: !php/const Capco\AppBundle\Enum\PostAffiliation::OWNER
                description: 'Posts that are owned by the authenticated user.'
