InternalMailingListAffiliation:
    type: enum
    config:
        name: MailingListAffiliation
        description: 'The affiliation of a user to a mailing list'
        values:
            OWNER:
                value: !php/const Capco\AppBundle\Enum\MailingListAffiliation::OWNER
                description: 'Mailing lists that are owned by the authenticated user.'
