InternalEventOrderField:
    type: enum
    config:
        name: EventOrderField
        description: 'Ordering options for events returned from the connection.'
        values:
            END_AT:
                value: !php/const Capco\AppBundle\Enum\EventOrderField::END_AT
                description: 'Order by the end date of the time range.'
            START_AT:
                value: !php/const Capco\AppBundle\Enum\EventOrderField::START_AT
                description: 'Order by the start date of the time range.'
