InternalPlatformAnalyticsTrafficSourceType:
    type: enum
    config:
        name: PlatformAnalyticsTrafficSourceType
        description: 'Represent a type of a traffic source'
        values:
            SEARCH_ENGINE:
                value: !php/const Capco\AppBundle\Enum\PlatformAnalyticsTrafficSourceType::SEARCH_ENGINE
                description: 'The traffic source came from a search engine'
            DIRECT:
                value: !php/const Capco\AppBundle\Enum\PlatformAnalyticsTrafficSourceType::DIRECT
                description: 'The traffic source came from a direct link'
            EXTERNAL_LINK:
                value: !php/const Capco\AppBundle\Enum\PlatformAnalyticsTrafficSourceType::EXTERNAL_LINK
                description: 'The traffic source came from an external link'
            SOCIAL_NETWORK:
                value: !php/const Capco\AppBundle\Enum\PlatformAnalyticsTrafficSourceType::SOCIAL_NETWORK
                description: 'The traffic source came from a social network'
            EMAIL:
                value: !php/const Capco\AppBundle\Enum\PlatformAnalyticsTrafficSourceType::EMAIL
                description: 'The traffic source came from an email'
