MainView:
    type: enum
    config:
        description: 'The main view : GRID, LIST or MAP'
        values:
            GRID:
                value: !php/const Capco\AppBundle\Enum\ViewConfiguration::GRID
                description: 'View proposals as GRID'
            LIST:
                value: !php/const Capco\AppBundle\Enum\ViewConfiguration::LIST
                description: 'View proposals as LIST'
            MAP:
                value: !php/const Capco\AppBundle\Enum\ViewConfiguration::MAP
                description: 'View proposals as MAP'
