MapTokenStyleVisibility:
    type: enum
    config:
        description: 'The visibility of a style for a map token'
        values:
            PUBLIC:
                value: !php/const Capco\AppBundle\Enum\MapTokenStyleVisibilityEnum::PUBLIC
                description: 'The style is public'
            PRIVATE:
                value: !php/const Capco\AppBundle\Enum\MapTokenStyleVisibilityEnum::PRIVATE
                description: 'The style is private'
