MapTokenProvider:
    type: enum
    config:
        description: 'The provider for a map token'
        values:
            MAPBOX:
                value: !php/const Capco\AppBundle\Enum\MapProviderEnum::MAPBOX
                description: 'Used for Mapbox service provider'
