MultipleChoiceQuestionValidationRulesTypes:
    type: enum
    config:
        description: 'Available types of validation rules'
        values:
            MIN:
                value: !php/const Capco\AppBundle\Enum\MultipleChoiceQuestionValidationRules::MIN
            EQUAL:
                value: !php/const Capco\AppBundle\Enum\MultipleChoiceQuestionValidationRules::EQUAL
            MAX:
                value: !php/const Capco\AppBundle\Enum\MultipleChoiceQuestionValidationRules::MAX
