GenderValue:
    type: enum
    config:
        description: '3 possible values'
        values:
            MALE:
                value: !php/const Capco\UserBundle\Entity\User::GENDER_MALE
            FEMALE:
                value: !php/const Capco\UserBundle\Entity\User::GENDER_FEMALE
            OTHER:
                value: !php/const Capco\UserBundle\Entity\User::GENDER_OTHER
