PostPublicationStatus:
    type: enum
    config:
        description: 'Available publication statuses for a post.'
        values:
            PUBLISHED:
                value: !php/const Capco\AppBundle\Enum\PostPublicationStatus::PUBLISHED
                description: 'Normal status, publicly visible'
            NOT_PUBLISHED:
                value: !php/const Capco\AppBundle\Enum\PostPublicationStatus::NOT_PUBLISHED
                description: 'Not publicly visible'
