ProjectVisibility:
    type: enum
    config:
        description: '4 possible values'
        values:
            ADMIN:
                value: !php/const Capco\AppBundle\Enum\ProjectVisibilityMode::VISIBILITY_ADMIN
                description: 'visible for group admin'
            CUSTOM:
                value: !php/const Capco\AppBundle\Enum\ProjectVisibilityMode::VISIBILITY_CUSTOM
                description: 'the project is restricted to users groups'
            ME:
                value: !php/const Capco\AppBundle\Enum\ProjectVisibilityMode::VISIBILITY_ME
                description: 'visible for me only'
            PUBLIC:
                value: !php/const Capco\AppBundle\Enum\ProjectVisibilityMode::VISIBILITY_PUBLIC
                description: 'visible for all'
