ProposalStepVoteType:
    type: enum
    config:
        description: 'Type of vote.'
        values:
            DISABLED:
                value: !php/const Capco\AppBundle\Enum\VoteType::DISABLED
            SIMPLE:
                value: !php/const Capco\AppBundle\Enum\VoteType::SIMPLE
            BUDGET:
                value: !php/const Capco\AppBundle\Enum\VoteType::BUDGET
