ProposalFormOrderField:
    type: enum
    config:
        description: 'Properties by which `ProposalForms` can be ordered.'
        values:
            UPDATED_AT:
                value: !php/const Capco\AppBundle\Enum\ProposalFormOrderField::UPDATED_AT
                description: 'Allows ordering a list of `ProposalForms` by when they have been updated.'
            CREATED_AT:
                value: !php/const Capco\AppBundle\Enum\ProposalFormOrderField::CREATED_AT
                description: 'Allows ordering a list of `ProposalForms` by when they have been created.'
