ProposalProgressState:
    type: enum
    config:
        description: "Possible values of a proposal's global progress state."
        values:
            IN_PROGRESS:
                value: !php/const Capco\AppBundle\Enum\ProposalStatementState::IN_PROGRESS
                description: 'The proposal is currently being edited'
            FAVOURABLE:
                value: !php/const Capco\AppBundle\Enum\ProposalStatementState::FAVOURABLE
                description: "The proposal's progress state is favourable."
            UNFAVOURABLE:
                value: !php/const Capco\AppBundle\Enum\ProposalStatementState::UNFAVOURABLE
                description: "The proposal's progress state is unfavourable."
            TOO_LATE:
                value: !php/const Capco\AppBundle\Enum\ProposalStatementState::TOO_LATE
                description: 'The evaluation of the proposal was not issued in time.'
            TODO:
                value: !php/const Capco\AppBundle\Enum\ProposalStatementState::TODO
                description: 'The evaluation of the proposal has not started yet.'
