ProposalAnalysisDecision:
    type: enum
    config:
        description: 'Available decisions value for a proposal analysis.'
        values:
            FAVOURABLE:
                value: !php/const Capco\AppBundle\Enum\ProposalStatementState::FAVOURABLE
                description: "The proposal's assessment state is favourable."
            UNFAVOURABLE:
                value: !php/const Capco\AppBundle\Enum\ProposalStatementState::UNFAVOURABLE
                description: "The proposal's assessment state is unfavourable."
            NONE:
                value: !php/const Capco\AppBundle\Enum\ProposalStatementState::NONE
                description: "The proposal's assessment state is unfavourable."
