ProposalAffiliation:
    type: enum
    config:
        description: The affiliation of a user to a proposal
        values:
            OWNER:
                value: !php/const Capco\AppBundle\Enum\ProposalAffiliations::OWNER
                description: 'Show only the proposals where the current user is an owner'
            EVALUER:
                value: !php/const Capco\AppBundle\Enum\ProposalAffiliations::EVALUER
                description: 'Show only the proposals where the current user is an evaluer'
