ProposalNewsErrorCode:
    type: enum
    inherits:
        - ProposalErrorCode
    config:
        name: ProposalNewsErrorCode
        description: 'Available errors on proposal news mutation'
        values:
            PROPOSAL_DOESNT_ALLOW_NEWS:
                value: !php/const Capco\AppBundle\GraphQL\Mutation\AddProposalNewsMutation::PROPOSAL_DOESNT_ALLOW_NEWS
                description: 'ROLE_USER cant add proposal news on this project'
            POST_NOT_FOUND:
                value: !php/const Capco\AppBundle\GraphQL\Mutation\UpdateProposalNewsMutation::POST_NOT_FOUND
                description: 'No post match your id'
            INVALID_DATA:
                value: !php/const Capco\AppBundle\GraphQL\Mutation\UpdateProposalNewsMutation::INVALID_DATA
                description: 'Invalid data in submitted form .'
            PROPOSAL_NOT_FOUND:
                value: !php/const Capco\AppBundle\GraphQL\Mutation\UpdateProposalNewsMutation::PROPOSAL_NOT_FOUND
                description: 'No proposal match on your post'
