ProposalArchivedUnitTime:
    type: enum
    config:
        name: ProposalArchivedUnitTime
        description: 'Available values for proposalArchivedUnitTime'
        values:
            DAYS:
                value: !php/const Capco\AppBundle\Enum\ProposalArchivedUnitTime::DAYS
                description: 'Set the archived value in days.'
            MONTHS:
                value: !php/const Capco\AppBundle\Enum\ProposalArchivedUnitTime::MONTHS
                description: 'Set the archived value in months.'
