ProposalSort:
    type: enum
    config:
        description: 'Value of a proposal sorting'
        values:
            OLD:
                value: !php/const Capco\AppBundle\Enum\ProposalSort::OLD
                description: 'Sort by the oldest ones first'
            LAST:
                value: !php/const Capco\AppBundle\Enum\ProposalSort::LAST
                description: 'Sort by the most recent ones first'
            VOTES:
                value: !php/const Capco\AppBundle\Enum\ProposalSort::VOTES
                description: 'Sort by the most voted ones first'
            LEAST_VOTE:
                value: !php/const Capco\AppBundle\Enum\ProposalSort::LEAST_VOTE
                description: 'Sort by the least voted ones first'
            COMMENTS:
                value: !php/const Capco\AppBundle\Enum\ProposalSort::COMMENTS
                description: 'Sort by the most commented first'
            RANDOM:
                value: !php/const Capco\AppBundle\Enum\ProposalSort::RANDOM
                description: 'Sort randomly'
            CHEAP:
                value: !php/const Capco\AppBundle\Enum\ProposalSort::CHEAP
                description: 'Sort by the cheap ones first'
            EXPENSIVE:
                value: !php/const Capco\AppBundle\Enum\ProposalSort::EXPENSIVE
                description: 'Sort by the expensive ones first'
