ProposalDecisionState:
    type: enum
    config:
        description: "Possible values of a proposal's decision state."
        values:
            IN_PROGRESS:
                value: !php/const Capco\AppBundle\Enum\ProposalStatementState::IN_PROGRESS
                description: "The proposal's decision is currently being edited"
            DONE:
                value: !php/const Capco\AppBundle\Enum\ProposalStatementState::DONE
                description: "The proposal's related decision state is favourable."
