ProposalPublicationStatus:
    type: enum
    config:
        description: 'Available statuses'
        values:
            PUBLISHED:
                value: !php/const Capco\AppBundle\Enum\ProposalPublicationStatus::PUBLISHED
                description: 'Publicly visible'
            TRASHED:
                value: !php/const Capco\AppBundle\Enum\ProposalPublicationStatus::TRASHED
                description: 'Publicly visible in the trash bin'
            TRASHED_NOT_VISIBLE:
                value: !php/const Capco\AppBundle\Enum\ProposalPublicationStatus::TRASHED_NOT_VISIBLE
                description: 'In the trash bin, content not visible'
            DELETED:
                value: !php/const Capco\AppBundle\Enum\ProposalPublicationStatus::DELETED
                description: 'Not publicly visible, deleted by author'
            DRAFT:
                value: !php/const Capco\AppBundle\Enum\ProposalPublicationStatus::DRAFT
                description: 'Draft, not publicly visible, only showed for his author.'
            UNPUBLISHED:
                value: !php/const Capco\AppBundle\Enum\ProposalPublicationStatus::UNPUBLISHED
                description: 'Visible by author only.'
            ARCHIVED:
                value: !php/const Capco\AppBundle\Enum\ProposalPublicationStatus::ARCHIVED
                description: 'Proposal archived.'
