ProposalImportsErrorCode:
    type: enum
    config:
        name: ProposalImportsErrorCode
        description: 'Available errors on proposal news mutation'
        values:
            PROPOSAL_FORM_NOT_FOUND:
                value: !php/const Capco\AppBundle\GraphQL\Mutation\AddProposalsFromCsvMutation::PROPOSAL_FORM_NOT_FOUND
                description: 'No proposal form match your id'
            BAD_DATA_MODEL:
                value: !php/const Capco\AppBundle\GraphQL\Mutation\AddProposalsFromCsvMutation::BAD_DATA_MODEL
                description: 'CSV file has bad header'
            EMPTY_FILE:
                value: !php/const Capco\AppBundle\GraphQL\Mutation\AddProposalsFromCsvMutation::EMPTY_FILE
                description: 'Given CSV file is empty'
            TOO_MUCH_LINES:
                value: !php/const Capco\AppBundle\GraphQL\Mutation\AddProposalsFromCsvMutation::TOO_MUCH_LINES
                description: 'Given CSV file contain over 501 lines'
            VIEWER_NOT_ALLOWED:
                value: !php/const Capco\AppBundle\GraphQL\Mutation\AddProposalsFromCsvMutation::VIEWER_NOT_ALLOWED
                description: 'Viewer is not allowed to import proposals'
