ProposalsState:
    type: enum
    config:
        description: 'Possible values to filters a list of proposals based on their state.'
        values:
            ALL:
                value: !php/const Capco\AppBundle\Enum\ProposalsState::ALL
                description: 'Show all proposals'
            PUBLISHED:
                value: !php/const Capco\AppBundle\Enum\ProposalsState::PUBLISHED
                description: 'Show only published proposals'
            TRASHED:
                value: !php/const Capco\AppBundle\Enum\ProposalsState::TRASHED
                description: 'Show only trashed proposals'
            DRAFT:
                value: !php/const Capco\AppBundle\Enum\ProposalsState::DRAFT
                description: 'Show only drafted proposals'
            ARCHIVED:
                value: !php/const Capco\AppBundle\Enum\ProposalsState::ARCHIVED
                description: 'Show only archived proposals'
