QuestionnaireType:
    type: enum
    config:
        description: 'Available questionnaire types.'
        values:
            QUESTIONNAIRE:
                value: !php/const Capco\AppBundle\Enum\QuestionnaireType::QUESTIONNAIRE
                description: 'Draft are allowed.'
            VOTING:
                value: !php/const Capco\AppBundle\Enum\QuestionnaireType::VOTING
                description: 'Draft are not allowed.'
            QUESTIONNAIRE_ANALYSIS:
                value: !php/const Capco\AppBundle\Enum\QuestionnaireType::QUESTIONNAIRE_ANALYSIS
                description: 'Questionnaire that are used in analysis step.'
