QuestionTypeValue:
    type: enum
    config:
        description: 'Value of type of question'
        values:
            text:
                value: !php/const Capco\AppBundle\Entity\Questions\AbstractQuestion::QUESTION_TYPE_SIMPLE_TEXT
            textarea:
                value: !php/const Capco\AppBundle\Entity\Questions\AbstractQuestion::QUESTION_TYPE_MULTILINE_TEXT
            editor:
                value: !php/const Capco\AppBundle\Entity\Questions\AbstractQuestion::QUESTION_TYPE_EDITOR
            radio:
                value: !php/const Capco\AppBundle\Entity\Questions\AbstractQuestion::QUESTION_TYPE_RADIO
            select:
                value: !php/const Capco\AppBundle\Entity\Questions\AbstractQuestion::QUESTION_TYPE_SELECT
            checkbox:
                value: !php/const Capco\AppBundle\Entity\Questions\AbstractQuestion::QUESTION_TYPE_CHECKBOX
            ranking:
                value: !php/const Capco\AppBundle\Entity\Questions\AbstractQuestion::QUESTION_TYPE_RANKING
            medias:
                value: !php/const Capco\AppBundle\Entity\Questions\AbstractQuestion::QUESTION_TYPE_MEDIAS
            button:
                value: !php/const Capco\AppBundle\Entity\Questions\AbstractQuestion::QUESTION_TYPE_BUTTON
            number:
                value: !php/const Capco\AppBundle\Entity\Questions\AbstractQuestion::QUESTION_TYPE_NUMBER
            section:
                value: !php/const Capco\AppBundle\Entity\Questions\AbstractQuestion::QUESTION_TYPE_SECTION
            siret:
                value: !php/const Capco\AppBundle\Entity\Questions\AbstractQuestion::QUESTION_TYPE_SIRET
            rna:
                value: !php/const Capco\AppBundle\Entity\Questions\AbstractQuestion::QUESTION_TYPE_RNA
            majority:
                value: !php/const Capco\AppBundle\Entity\Questions\AbstractQuestion::QUESTION_TYPE_MAJORITY_DECISION
