ReportingType:
    type: enum
    config:
        description: 'Type of reporting'
        values:
            SEX:
                value: !php/const Capco\AppBundle\Enum\ReportingType::SEX
                description: 'The associated contribution has been flagged as sexual content'
            OFF:
                value: !php/const Capco\AppBundle\Enum\ReportingType::OFF
                description: 'The associated contribution has been flagged as offending content'
            SPAM:
                value: !php/const Capco\AppBundle\Enum\ReportingType::SPAM
                description: 'The associated contribution has been flagged as spam'
            ERROR:
                value: !php/const Capco\AppBundle\Enum\ReportingType::ERROR
                description: 'The associated contribution has been flagged as erroneous'
            OFF_TOPIC:
                value: !php/const Capco\AppBundle\Enum\ReportingType::OFF_TOPIC
                description: 'The associated contribution has been flagged as off topic'
