ResponsesOrderField:
    type: enum
    config:
        description: 'Properties by which responses can be ordered'
        values:
            CREATED_AT:
                value: !php/const Capco\AppBundle\Enum\ResponsesOrderField::CREATED_AT
                description: 'Allows ordering a list of responses by its creation date.'
            READABILITY:
                value: !php/const Capco\AppBundle\Enum\ResponsesOrderField::READABILITY
                description: 'Allows ordering a list of responses by its readability score.'
            CATEGORY:
                value: !php/const Capco\AppBundle\Enum\ResponsesOrderField::CATEGORY
                description: 'Allows ordering a list of responses by its category.'
