SelectSenderEmailErrorCode:
    type: enum
    config:
        description: 'Possible errors on selectSenderDomain mutation.'
        values:
            UNKNOWN_SENDER_EMAIL:
                value: !php/const Capco\AppBundle\GraphQL\Mutation\Mailing\SelectSenderEmailMutation::UNKNOWN_SENDER_EMAIL
                description: 'No `SenderEmail` matching your id.'
