SendSmsProposalVoteErrorCode:
    type: enum
    config:
        name: SendSmsProposalVoteErrorCode
        description: 'Available errors for an `sendSmsProposalVote` mutation.'
        values:
            INVALID_NUMBER:
                value: !php/const Capco\AppBundle\Helper\TwilioHelper::INVALID_NUMBER
                description: 'The given number is invalid.'
            TWILIO_API_ERROR:
                value: !php/const Capco\AppBundle\Helper\TwilioHelper::TWILIO_API_ERROR
                description: 'An error occured while calling twilio api.'
            PHONE_SHOULD_BE_MOBILE_NUMBER:
                value: !php/const Capco\AppBundle\Enum\UserPhoneErrors::PHONE_SHOULD_BE_MOBILE_NUMBER
                description: 'Given phone number should be a mobile number.'
            PHONE_INVALID_LENGTH:
                value: !php/const Capco\AppBundle\Enum\UserPhoneErrors::PHONE_INVALID_LENGTH
                description: 'Given phone number has incorrect length.'
            PHONE_ALREADY_USED_BY_ANOTHER_USER:
                value: !php/const Capco\AppBundle\Enum\UserPhoneErrors::PHONE_ALREADY_USED_BY_ANOTHER_USER
                description: 'Given phone number is already used by another user.'
            RETRY_LIMIT_REACHED:
                value: !php/const Capco\AppBundle\GraphQL\Mutation\Sms\SendSmsProposalVoteMutation::RETRY_LIMIT_REACHED
                description: 'The user reached the retry limit.'
