SenderEmailDomainService:
    type: enum
    config:
        description: 'Possible types for SenderEmailDomain.'
        values:
            MANDRILL:
                value: !php/const Capco\AppBundle\Entity\ExternalServiceConfiguration::MAILER_MANDRILL
                description: 'Choice of the external mailer client : mandrill or mailjet.'
            MAILJET:
                value: !php/const Capco\AppBundle\Entity\ExternalServiceConfiguration::MAILER_MAILJET
                description: 'Choice of the external mailer client : mandrill or mailjet.'
