SendSmsPhoneValidationCodeErrorCode:
    type: enum
    config:
        name: SendSmsPhoneValidationCodeErrorCode
        description: 'Available errors for an `sendSmsPhoneValidationCode` mutation.'
        values:
            INVALID_NUMBER:
                value: !php/const Capco\AppBundle\Helper\TwilioSmsProvider::INVALID_NUMBER
                description: 'The given number is invalid'
            RETRY_LIMIT_REACHED:
                value: !php/const Capco\AppBundle\GraphQL\Mutation\Sms\SendSmsPhoneValidationCodeMutation::RETRY_LIMIT_REACHED
                description: 'The user reached the retry limit of 2 within a minute'
            PHONE_ALREADY_CONFIRMED:
                value: !php/const Capco\AppBundle\GraphQL\Mutation\Sms\SendSmsPhoneValidationCodeMutation::PHONE_ALREADY_CONFIRMED
                description: 'The user has already confirmed his phone number'
            UNAUTHORIZED:
                value: !php/const Capco\AppBundle\Helper\OrangeSmsProvider::UNAUTHORIZED
                description: 'The user is unauthorized'
            RATE_LIMIT_EXCEEDED:
                value: !php/const Capco\AppBundle\Helper\OrangeSmsProvider::RATE_LIMIT_EXCEEDED
                description: 'The rate limit for requests has been exceeded'
            SERVER_ERROR:
                value: !php/const Capco\AppBundle\Helper\OrangeSmsProvider::SERVER_ERROR
                description: 'A server error occurred while processing the request'
            UNKNOWN_ERROR:
                value: !php/const Capco\AppBundle\Helper\OrangeSmsProvider::UNKNOWN_ERROR
                description: 'An unknown error occurred'
            NOT_FOUND:
                value: !php/const Capco\AppBundle\Helper\OrangeSmsProvider::NOT_FOUND
                description: 'The requested resource was not found'
            NOT_VALID_CODE:
                value: !php/const Capco\AppBundle\Helper\OrangeSmsProvider::NOT_VALID_CODE
                description: 'The provided code is not valid'
            TWILIO_API_ERROR:
                value: !php/const Capco\AppBundle\Helper\TwilioSmsProvider::TWILIO_API_ERROR
                description: 'An error occured while calling twilio api'
