SmsOrdersFilters:
    type: enum
    config:
        name: SmsOrdersFilters
        description: 'Available filters for `SmsOrders` query.'
        values:
            PROCESSED:
                value: !php/const Capco\AppBundle\Enum\SmsOrdersFilters::PROCESSED
                description: 'Filter by processed orders.'
            UNPROCESSED:
                value: !php/const Capco\AppBundle\Enum\SmsOrdersFilters::UNPROCESSED
                description: 'Filter by unprocessed orders.'