SSOEnvironment:
    type: enum
    config:
        description: 'Possible environments for a SSO Configuration.'
        values:
            NONE:
                value: !php/const Capco\AppBundle\DBAL\Enum\EnumSSOEnvironmentType::NONE
                description: 'Unset mode.'
            TESTING:
                value: !php/const Capco\AppBundle\DBAL\Enum\EnumSSOEnvironmentType::TESTING
                description: 'Integration mode for resource owner validation.'
            PRODUCTION:
                value: !php/const Capco\AppBundle\DBAL\Enum\EnumSSOEnvironmentType::PRODUCTION
                description: 'Production mode.'
