SubscriptionTypeValue:
    type: enum
    config:
        description: '3 possible values for a subscription.'
        values:
            ALL:
                value: !php/const Capco\AppBundle\Enum\FollowerSubscriptionType::ALL
                description: 'Get all notifications for this subscription'
            ESSENTIAL:
                value: !php/const Capco\AppBundle\Enum\FollowerSubscriptionType::ESSENTIAL
                description: 'Get essentials notifications for this subscription'
            MINIMAL:
                value: !php/const Capco\AppBundle\Enum\FollowerSubscriptionType::MINIMAL
                description: 'Get minimal notifications for this subscription'
