TranslationLocale:
    type: enum
    config:
        description: 'A translation locale'
        values:
            EN_GB:
                value: !php/const Capco\AppBundle\Enum\TranslationLocale::EN_GB
                description: 'English - UNITED KINGDOM locale'
            FR_FR:
                value: !php/const Capco\AppBundle\Enum\TranslationLocale::FR_FR
                description: 'French - FRANCE locale'
            ES_ES:
                value: !php/const Capco\AppBundle\Enum\TranslationLocale::ES_ES
                description: 'Spanish - SPAIN locale'
            DE_DE:
                value: !php/const Capco\AppBundle\Enum\TranslationLocale::DE_DE
                description: 'German - GERMANY locale'
            NL_NL:
                value: !php/const Capco\AppBundle\Enum\TranslationLocale::NL_NL
                description: 'Dutch - NETHERLANDS locale'
            SV_SE:
                value: !php/const Capco\AppBundle\Enum\TranslationLocale::SV_SE
                description: 'Swedish - SWEDEN locale'
            EU_EU:
                value: !php/const Capco\AppBundle\Enum\TranslationLocale::EU_EU
                description: 'Basque - EUSKADIA locale'
            OC_OC:
                value: !php/const Capco\AppBundle\Enum\TranslationLocale::OC_OC
                description: 'Gascon - OCCITAN locale'
            UR_IN:
                value: !php/const Capco\AppBundle\Enum\TranslationLocale::UR_IN
                description: 'Recette - RECETTE locale'
