TrashableStatus:
    type: enum
    config:
        description: 'Different trashable status.'
        values:
            INVISIBLE:
                value: !php/const Capco\AppBundle\Entity\Interfaces\Trashable::STATUS_INVISIBLE
                description: 'Content is not visible.'
            VISIBLE:
                value: !php/const Capco\AppBundle\Entity\Interfaces\Trashable::STATUS_VISIBLE
                description: 'Content is visible.'
