UpdateSiteParameterErrorCode:
    type: enum
    config:
        name: UpdateSiteParameterErrorCode
        description: 'Available errors for an `updateSiteParameter` mutation.'
        values:
            INVALID_VALUE:
                value: !php/const Capco\AppBundle\GraphQL\Mutation\UpdateSiteParameterMutation::INVALID_VALUE
                description: 'The given value is invalid.'
