UpdateProfilePersonalDataErrorCode:
    type: enum
    config:
        name: UpdateProfilePersonalDataErrorCode
        description: 'Available errors for an `personalData` mutation.'
        values:
            CANT_UPDATE:
                value: !php/const Capco\AppBundle\GraphQL\Mutation\UpdateProfilePersonalDataMutation::CANT_UPDATE
                description: 'The update failed'
            PHONE_SHOULD_BE_MOBILE_NUMBER:
                value: !php/const Capco\AppBundle\Enum\UserPhoneErrors::PHONE_SHOULD_BE_MOBILE_NUMBER
                description: 'The given phone should be a mobile phone number.'
            PHONE_ALREADY_USED_BY_ANOTHER_USER:
                value: !php/const Capco\AppBundle\Enum\UserPhoneErrors::PHONE_ALREADY_USED_BY_ANOTHER_USER
                description: 'The given phone is already used by another user.'
            PHONE_INVALID_LENGTH:
                value: !php/const Capco\AppBundle\Enum\UserPhoneErrors::PHONE_INVALID_LENGTH
                description: 'The given phone should be 10 digits.'