UpdateProposalStepPaperVoteCounterErrorCode:
    type: enum
    config:
        name: UpdateProposalStepPaperVoteCounterErrorCode
        description: 'Available errors on UpdateProposalStepPaperVoteCounter mutation.'
        values:
            PROPOSAL_NOT_FOUND:
                value: !php/const Capco\AppBundle\GraphQL\Mutation\Proposal\UpdateProposalStepPaperVoteCounterMutation::PROPOSAL_NOT_FOUND
                description: 'The proposal does not exist.'
            STEP_NOT_FOUND:
                value: !php/const Capco\AppBundle\GraphQL\Mutation\Proposal\UpdateProposalStepPaperVoteCounterMutation::STEP_NOT_FOUND
                description: 'The step does not exist or is neither a collect nor selection step.'
            STEP_NOT_VOTABLE:
                value: !php/const Capco\AppBundle\GraphQL\Mutation\Proposal\UpdateProposalStepPaperVoteCounterMutation::STEP_NOT_VOTABLE
                description: 'The step is not votable.'
