UserOrderField:
    type: enum
    config:
        description: 'Properties by which users connections can be ordered'
        values:
            CREATED_AT:
                value: !php/const Capco\AppBundle\Enum\UserOrderField::CREATED_AT
                description: 'Allows ordering a list of users by when they were created.'
            ACTIVITY:
                value: !php/const Capco\AppBundle\Enum\UserOrderField::ACTIVITY
                description: 'Allowing ordering a list of user by their activity.'
