UserInviteStatus:
    type: enum
    config:
        description: 'The invitation status'
        values:
            PENDING:
                value: !php/const Capco\AppBundle\Enum\UserInviteStatus::PENDING
                description: 'The invitation is still pending.'
            EXPIRED:
                value: !php/const Capco\AppBundle\Enum\UserInviteStatus::EXPIRED
                description: 'The invitation has expired.'
            FAILED:
                value: !php/const Capco\AppBundle\Enum\UserInviteStatus::FAILED
                description: 'Sending the invitation failed.'
            ACCEPTED:
                value: !php/const Capco\AppBundle\Enum\UserInviteStatus::ACCEPTED
                description: 'The invitation has been accepted.'
