VerifyUserPhoneNumberErrorCode:
    type: enum
    config:
        name: VerifyUserPhoneNumberErrorCode
        description: 'Available errors for an `verifyUserPhoneNumber` mutation.'
        values:
            PHONE_ALREADY_CONFIRMED:
                value: !php/const Capco\AppBundle\GraphQL\Mutation\Sms\VerifyUserPhoneNumberMutation::PHONE_ALREADY_CONFIRMED
                description: 'The given phone is already confirmed.'
            CODE_EXPIRED:
                value: !php/const Capco\AppBundle\Helper\TwilioHelper::CODE_EXPIRED
                description: 'The given given code is expired.'
            CODE_NOT_VALID:
                value: !php/const Capco\AppBundle\Helper\TwilioHelper::CODE_NOT_VALID
                description: 'The given code is not valid.'
            TWILIO_API_ERROR:
                value: !php/const Capco\AppBundle\Helper\TwilioHelper::TWILIO_API_ERROR
                description: 'An error occured while calling twilio api.'
