VersionOrderField:
    type: enum
    config:
        description: 'Properties by which version connections can be ordered'
        values:
            PUBLISHED_AT:
                value: !php/const Capco\AppBundle\Enum\VersionOrderField::PUBLISHED_AT
                description: 'Allows ordering a list of versions by when they were published.'
            VOTES:
                value: !php/const Capco\AppBundle\Enum\VersionOrderField::VOTES
                description: 'Allows ordering a list of versions by the number of votes it have.'
            ARGUMENTS:
                value: !php/const Capco\AppBundle\Enum\VersionOrderField::ARGUMENTS
                description: 'Allows ordering a list of versions by the number of arguments it have.'
            VOTES_OK:
                value: !php/const Capco\AppBundle\Enum\VersionOrderField::VOTES_OK
                description: 'Allows ordering a list of versions by the number of votes ok it have.'
            RANDOM:
                value: !php/const Capco\AppBundle\Enum\VersionOrderField::RANDOM
                description: 'Allows ordering a list of versions randomly.'
