YesNoPairedVoteValue:
    type: enum
    config:
        description: '3 possible values'
        values:
            YES:
                value: !php/const Capco\AppBundle\Entity\OpinionVote::VOTE_OK
            NO:
                value: !php/const Capco\AppBundle\Entity\OpinionVote::VOTE_NOK
            MITIGE:
                value: !php/const Capco\AppBundle\Entity\OpinionVote::VOTE_MITIGE
