services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Capco\AppBundle\Helper\:
        resource: '%kernel.project_dir%/src/Capco/AppBundle/Helper/*'
        exclude: '%kernel.project_dir%/src/Capco/AppBundle/Helper/{RedisStorageHelper.php}'

    Capco\AppBundle\Helper\RedisStorageHelper:
        arguments: ['@snc_redis.default']

    Capco\AppBundle\Helper\TwilioClient:
        arguments:
            $twilioSid: '%twilio_sid%'
            $twilioToken: '%twilio_token%'

    Capco\AppBundle\Helper\OrangeClient:
        arguments:
            $clientId: '%orange_client_id%'
            $clientSecret: '%orange_client_secret%'

    Capco\AppBundle\Helper\TwilioSmsProvider:
        arguments: ['@Capco\AppBundle\Helper\TwilioClient']
