security:
    encoders:
        Capco\UserBundle\Entity\User:
            algorithm: bcrypt
            cost: 12

    role_hierarchy:
        ROLE_MEDIATOR: [ROLE_USER]
        ROLE_PROJECT_ADMIN: [ROLE_USER]
        ROLE_ADMIN: [ROLE_USER, ROLE_SONATA_ADMIN, ROLE_PROJECT_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        SONATA:
            - ROLE_SONATA_PAGE_ADMIN_PAGE_EDIT # if you are using acl then this line must be commented
    access_control:
        - { path: ^/admin/alpha/project, roles: ROLE_USER }
        - { path: ^/admin/capco/app/project/.*/edit, roles: ROLE_ADMIN }
        - { path: ^/admin/capco/app/project, roles: ROLE_PROJECT_ADMIN }
        - { path: ^/admin/capco/app/proposalform, roles: ROLE_USER }
        - { path: ^/admin/capco/app/event, roles: ROLE_USER }
        - { path: ^/admin/capco/app/proposal/.*/edit, roles: ROLE_USER }
        - { path: ^/admin/capco/app/post, roles: ROLE_USER }
        - { path: ^/admin/capco/app/questionnaire, roles: ROLE_USER }
        - { path: ^/admin/dashboard, roles: ROLE_PROJECT_ADMIN }
        - { path: ^/admin/core/get-autocomplete-items, roles: ROLE_PROJECT_ADMIN }
        - { path: ^/admin/mailingList/, roles: ROLE_USER }
        - { path: ^/admin/mailingCampaign/, roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_ADMIN }
    providers:
        fos_userbundle:
            id: Capco\UserBundle\Security\Core\User\UserEmailProvider
        simple_preauth:
            id: Capco\UserBundle\Security\Core\User\SimplePreAuthenticatorUserProvider
        public_api_key_user_provider:
            id: Capco\AppBundle\PublicApi\PublicApiKeyUserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # This is our Public API authenticated with Personal Access Token
        graphql_public:
            pattern: ^/graphql$
            provider: public_api_key_user_provider
            stateless: true
            anonymous: true # Right now anonymous are allowed
            simple_preauth:
                authenticator: Capco\AppBundle\PublicApi\PublicApiKeyAuthenticator

        # The rest is authenticated with cookies
        main:
            pattern: ^/
            provider: fos_userbundle
            anonymous: true
            simple_preauth:
                authenticator: Capco\UserBundle\Authenticator\SimplePreAuthenticator
                provider: simple_preauth
            json_login:
                check_path: /login_check
                remember_me: true
                failure_handler: Capco\AppBundle\EventListener\AuthenticationHandler
            oauth:
                resource_owners:
                    facebook: /login/check-facebook
                    openid: /login/check-openid
                    franceconnect: /login/check-franceconnect
                login_path: /
                oauth_user_provider:
                    service: Capco\UserBundle\Security\Core\User\OauthUserProvider
            remember_me:
                always_remember_me: false
                secret: '%remember_secret%'
                lifetime: '%env(SYMFONY_SESSION_TIMEOUT_SECONDS)%'
                path: /
                domain: ~
            logout:
                path: /logout
                success_handler: Capco\UserBundle\Security\Http\Logout\LogoutSuccessHandler
    access_decision_manager:
        strategy: unanimous
