services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Capco\AppBundle\Validator\Constraints\CheckEmailDomainValidator:
        tags:
            - { name: validator.constraint_validator, alias: capco.check_email_domain.validator }
    Capco\AppBundle\Validator\Constraints\HasResponsesToRequiredQuestionsValidator:
        tags:
            - { name: validator.constraint_validator, alias: has_required_responses.validator }
    Capco\AppBundle\Validator\Constraints\DidNotAlreadyVoteValidator:
        tags:
            - { name: validator.constraint_validator, alias: already_vote.validator }
    Capco\AppBundle\Validator\Constraints\EmailDoesNotBelongToUserValidator:
        tags:
            - { name: validator.constraint_validator, alias: email_belongs_not.validator }
    Capco\AppBundle\Validator\Constraints\EndAfterStartValidator:
        tags:
            - { name: validator.constraint_validator, alias: end_after_start.validator }
    Capco\AppBundle\Validator\Constraints\HasThemeIfActivatedValidator:
        tags:
            - { name: validator.constraint_validator, alias: has_theme_if_activated.validator }
    Capco\AppBundle\Validator\Constraints\CheckExternalLinkValidator:
        tags:
            - { name: validator.constraint_validator, alias: check_external_link.validator }
    Capco\AppBundle\Validator\Constraints\IsSocialNetworkUrlValidator:
        tags:
            - { name: validator.constraint_validator, alias: is_social_network_url.validator }
    Capco\AppBundle\Validator\Constraints\HasUnlistedEmailValidator:
        tags:
            - { name: validator.constraint_validator, alias: unlisted_email.validator }
    Capco\AppBundle\Validator\Constraints\HasEnoughCreditsToVoteValidator:
        tags:
            - { name: validator.constraint_validator, alias: has_enough_credits.validator }
    Capco\AppBundle\Validator\Constraints\CaptchaValidator:
        tags:
            - { name: validator.constraint_validator, alias: captcha.validator }
    Capco\AppBundle\Validator\Constraints\HasThemeIfMandatoryValidator:
        tags:
            - { name: validator.constraint_validator, alias: has_theme_if_mandatory.validator }
    Capco\AppBundle\Validator\Constraints\HasCategoryIfMandatoryValidator:
        tags:
            - { name: validator.constraint_validator, alias: has_category_if_mandatory.validator }
    Capco\AppBundle\Validator\Constraints\CheckRegisterValidator:
        tags:
            - { name: validator.constraint_validator, alias: check_register.validator }
    Capco\AppBundle\Validator\Constraints\HasValidAddressValidator:
        tags:
            - { name: validator.constraint_validator, alias: has_valid_address.validator }
    Capco\AppBundle\Validator\Constraints\HasOnlyOneSelectionStepAllowingProgressStepsValidator:
        tags:
            - {
                  name: validator.constraint_validator,
                  alias: has_only_one_selection_step_allowing_progress_step.validator,
              }
    Capco\AppBundle\Validator\Constraints\HasDistrictIfMandatoryValidator:
        tags:
            - { name: validator.constraint_validator, alias: has_district_if_mandatory.validator }
    Capco\AppBundle\Validator\Constraints\HasAddressIfMandatoryValidator:
        tags:
            - { name: validator.constraint_validator, alias: has_address_if_mandatory.validator }
    Capco\AppBundle\Validator\Constraints\NotThrowableEmailValidator:
        tags:
            - { name: validator.constraint_validator, alias: capco.not_throwable_email.validator }
    Capco\AppBundle\Validator\Constraints\PasswordComplexityValidator:
        tags:
            - { name: validator.constraint_validator, alias: password_complexity.validator }
    Capco\AppBundle\Validator\Constraints\CheckGeoJsonValidator:
        tags:
            - { name: validator.constraint_validator, alias: geojson.validator }
    Capco\AdminBundle\Validator\Constraints\LessThanIfMetaDescriptionValidator:
        tags:
            - {
                  name: validator.constraint_validator,
                  alias: less_than_if_meta_description.validator,
              }
    Capco\AppBundle\Validator\Constraints\HasUserGroupIfVisibilityGroupValidator:
        tags:
            - { name: validator.constraint_validator, alias: has_user_group_if_mandatory.validator }
    Capco\AppBundle\Validator\Constraints\VoteMinValidator:
        tags:
            - { name: validator.constraint_validator, alias: vote_min.validator }
    Capco\AppBundle\Validator\Constraints\CheckColorValidator:
        tags:
            - { name: validator.constraint_validator, alias: check_color.validator }
    Capco\AppBundle\Validator\Constraints\CheckMapCenterValidator:
        tags:
            - { name: validator.constraint_validator, alias: map_center.validator }
    Capco\AppBundle\Validator\Constraints\CheckDebateAnonymousParticipationHashValidator:
        tags:
            - {
                  name: validator.constraint_validator,
                  alias: check_debate_anonymous_participation_hash.validator,
              }

    Capco\AppBundle\Validator\Constraints\CheckIdentificationCodeValidator:
        tags:
            - { name: validator.constraint_validator, alias: check_identification_code.validator }

    Capco\AppBundle\Validator\Constraints\CommentHasAuthorValidator:
        tags:
            - { name: validator.constraint_validator, alias: comment_has_author.validator }

    Capco\AppBundle\Validator\Constraints\HasAuthorValidator:
        tags:
            - { name: validator.constraint_validator, alias: has_author.validator }

    Capco\AppBundle\Validator\Constraints\CheckPhoneNumberValidator:
        tags:
            - { name: validator.constraint_validator, alias: check_phone_number.validator }

    Capco\AppBundle\Validator\Constraints\CheckCustomDomainValidator:
        tags:
            - { name: validator.constraint_validator, alias: check_custom_domain.validator }

    Capco\AppBundle\Validator\Constraints\PendingOrganizationInvitationValidator:
        tags:
            - {
                  name: validator.constraint_validator,
                  alias: pending_organization_invitation.validator,
              }
