PreviewWithFollowers:
    type: object
    decorator: true
    config:
        name: WithFollowers
        fields:
            followers:
                type: 'PreviewFollowerConnection'
                argsBuilder: 'Relay::ForwardConnection'
                description: 'Followers connection'
            viewerFollowingConfiguration:
                access: "@=hasRole('ROLE_USER')"
                type: 'SubscriptionTypeValue'
                description: 'Identifies the viewer following configuration on the entity.'
            viewerIsFollowing:
                access: "@=hasRole('ROLE_USER')"
                type: 'Boolean!'
                description: 'Identifies if the viewer is following the entity.'
