PreviewProposalDecision:
    type: object
    inherits:
        - Timestampable
    config:
        description: 'A proposal decision.'
        name: ProposalDecision
        fields:
            id:
                builder: 'Relay::GlobalId'
                builderConfig:
                    typeName: ProposalDecision
                description: "The proposal's decision id."
            proposal:
                type: 'PreviewProposal!'
                description: 'The related proposal.'
            decisionMaker:
                type: 'PreviewUser!'
                resolve: '@=value.getUpdatedBy()'
                description: 'The last updated by a decision-maker.'
            isApproved:
                type: 'Boolean!'
                description: 'The current state of the decision.'
            estimatedCost:
                type: 'Int'
                description: 'The estimated cost of the related proposal in €.'
            post:
                type: 'PreviewOfficialResponse!'
                description: 'The related official response.'
                deprecationReason: 'Field "post" will be removed, Use "officialResponse" instead.'
            officialResponse:
                type: 'PreviewOfficialResponse!'
                description: 'The related official response.'
            state:
                type: 'ProposalDecisionState!'
                description: 'The current status of the decision on the proposal'
            refusedReason:
                type: 'ProposalStepStatus'
                description: "The step's related status assigned to the proposal."
