PreviewDistrictTranslation:
    type: object
    config:
        name: DistrictTranslation
        description: 'A translation of a District.'
        fields:
            locale:
                type: 'String!'
            name:
                type: 'String!'
            slug:
                type: 'String!'
            titleOnMap:
                type: 'String'
            description:
                type: 'String'
                description: 'The description of the district.'
