PreviewProjectDistrictPositioner:
    type: object
    config:
        name: ProjectDistrictPositioner
        fields:
            district:
                type: 'PreviewProjectDistrict!'
            project:
                type: 'PreviewProject!'
            position:
                type: 'Int!'
