CreateProjectDistrictPayload:
    type: relay-mutation-payload
    config:
        fields:
            district:
                type: 'InternalProjectDistrict'
            districtEdge:
                type: 'InternalProjectDistrictEdge'
                description: 'The edge from the project district connection.'
            userErrors:
                type: '[UserError!]!'
                description: 'An unsuccessful mutation will return one or more `UserError` objects.'
