DeleteGlobalDistrictPayload:
    type: relay-mutation-payload
    config:
        fields:
            deletedDistrictId:
                type: 'ID'
            userErrors:
                type: '[UserError!]!'
                description: 'An unsuccessful mutation will return one or more `UserError` objects.'
