FollowProjectDistrictPayload:
    type: relay-mutation-payload
    config:
        fields:
            projectDistrict:
                type: 'InternalProjectDistrict'
            followerEdge:
                type: 'FollowerEdge'
            errorCode:
                type: 'ProjectDistrictErrorCode'
