UpdateGlobalDistrictInput:
    type: input-object
    config:
        fields:
            id:
                type: ID!
            geojson:
                type: GeoJSON
                description: 'A GeoJSON format to display in map after.'
            displayedOnMap:
                type: Boolean
                defaultValue: false
                description: 'Should I display this on map?'
            border:
                type: BorderStyleInput
                description: 'The border style attached to this district.'
            background:
                type: BackgroundStyleInput
                description: 'The background style attached to this district.'
            translations:
                type: '[InternalDistrictTranslationInput!]!'
                description: 'The names of the district for each language'
            cover:
                type: 'ID'
                description: 'The district cover.'
