InternalGlobalDistrictConnection:
    type: relay-connection
    inherits:
        - PreviewGlobalDistrictConnection
    config:
        nodeType: InternalGlobalDistrict
        name: GlobalDistrictConnection
