InternalProjectDistrictConnection:
    type: relay-connection
    inherits:
        - PreviewProjectDistrictConnection
    config:
        nodeType: InternalProjectDistrict
        name: ProjectDistrictConnection
