MediatorConnection:
    type: relay-connection
    config:
        nodeType: InternalMediator!
        connectionFields:
            totalCount:
                type: Int!
                description: Identifies the total count of items in the connection.
