Requirement:
    type: interface
    config:
        description: 'A requirement'
        resolveType: '@=resolver("Capco\\AppBundle\\GraphQL\\Resolver\\Requirement\\RequirementTypeResolver", [value])'
        fields:
            id:
                builder: 'Relay::GlobalId'
                builderConfig:
                    typeName: Requirement
            viewerMeetsTheRequirement:
                type: 'Boolean!'
                access: "@=hasRole('ROLE_USER')"
                description: 'Does the viewer meets the requirement ?'
                resolve: '@=resolver("Capco\\AppBundle\\GraphQL\\Resolver\\Requirement\\ViewerMeetsTheRequirementResolver", [value, getUser()])'
            participantMeetsTheRequirement:
                type: 'Boolean!'
                description: 'Does the participant meets the requirement ?'
                args:
                    token:
                        type: 'String!'
                        description: 'The token associated to the Participant.'
                resolve: '@=resolver("Capco\\AppBundle\\GraphQL\\Resolver\\Requirement\\ParticipantMeetsTheRequirementResolver", [value, args])'
