EventReviewStatus:
    type: enum
    config:
        description: 'Event Review status'
        values:
            APPROVED:
                value: !php/const Capco\AppBundle\DBAL\Enum\EventReviewStatusType::APPROVED
                description: 'The review is in approved status.'
            AWAITING:
                value: !php/const Capco\AppBundle\DBAL\Enum\EventReviewStatusType::AWAITING
                description: 'The review is in awaiting status.'
            REFUSED:
                value: !php/const Capco\AppBundle\DBAL\Enum\EventReviewStatusType::REFUSED
                description: 'The review is in refused status.'
            PUBLISHED:
                value: !php/const Capco\AppBundle\DBAL\Enum\EventReviewStatusType::PUBLISHED
                description: 'The event is published'
            NOT_PUBLISHED:
                value: !php/const Capco\AppBundle\DBAL\Enum\EventReviewStatusType::NOT_PUBLISHED
                description: 'The event is not published'
            DELETED:
                value: !php/const Capco\AppBundle\DBAL\Enum\EventReviewStatusType::DELETED
                description: 'The event deleted'
