InternalTheme:
    type: object
    inherits:
        - PreviewTheme
        - UniformResourceLocatable
    config:
        name: Theme
        interfaces:
            - UniformResourceLocatable
        description: 'A theme'
        fields:
            url:
                resolve: '@=resolver("Capco\\AppBundle\\GraphQL\\Resolver\\Theme\\ThemeUrlResolver", [value])'
            translations:
                type: '[InternalThemeTranslation!]!'
