InternalProjectDistrictPositioner:
    type: object
    inherits:
        - PreviewProjectDistrictPositioner
    config:
        name: ProjectDistrictPositioner
        fields:
            district:
                type: 'InternalGlobalDistrict!'
            project:
                type: 'InternalProject!'
