InternalProposalDecision:
    type: object
    inherits:
        - PreviewProposalDecision
    config:
        description: 'A proposal decision.'
        name: ProposalDecision
        fields:
            proposal:
                type: 'InternalProposal!'
            decisionMaker:
                type: 'InternalUser!'
            post:
                type: 'InternalOfficialResponse'
                resolve: '@=value.getOfficialResponse()'
                deprecationReason: 'reason: "Replaced by OfficialResponse", Field "post" will be removed, Use "officialResponse" instead.'
            officialResponse:
                type: 'InternalOfficialResponse'
