InternalEventDistrictPositionerConnection:
  type: relay-connection
  config:
    name: EventDistrictPositionerConnection
    nodeType: InternalEventDistrictPositioner!
    connectionFields:
      totalCount:
        type: Int!
