InternalFacebookSSOConfiguration:
    type: object
    inherits:
        - Node
        - InternalSSOConfiguration
    config:
        interfaces:
            - Node
            - InternalSSOConfiguration
        name: FacebookSSOConfiguration
        description: 'Facebook SSO Configuration.'
        fields:
            id:
                description: 'The ID of an object.'
                builder: 'Relay::GlobalId'
                builderConfig:
                    typeName: FacebookSSOConfiguration
            clientId:
                access: "@=hasRole('ROLE_ADMIN')"
                type: 'String'
                description: 'Client ID.'
            secret:
                access: "@=hasRole('ROLE_ADMIN')"
                type: 'String'
                description: 'Secret key.'
