InternalWithProposals:
    type: object
    decorator: true
    inherits:
        - PreviewWithProposals
    config:
        fields:
            proposals:
                type: 'InternalProposalConnection!'
                args:
                    state:
                        type: 'ProposalsState'
                        description: 'The state of the proposals to filter by. If non-null, filters proposals with the given state.'
                    district:
                        type: 'ID'
                        description: 'ID of a ProposalDistrict to filter by. If non-null, filters proposals with the given district.'
                    userType:
                        type: 'ID'
                        description: 'ID of a UserType to filter by. If non-null, filters proposals with the given type of author.'
                    category:
                        type: 'ID'
                        description: 'ID of a ProposalCategory to filter by. If non-null, filters proposals with the given category.'
                    status:
                        type: 'ID'
                        description: 'ID of a ProposalStatus to filter by. If non-null, filters proposals with the given status.'
                    theme:
                        type: 'ID'
                        description: 'ID of a Theme to filter by. If non-null, filters proposals with the given theme.'
                    term:
                        type: 'String'
                        description: 'If non-null, filters proposals with the given string to look for.'
                    reference:
                        type: 'String'
                    affiliations:
                        type: '[ProposalAffiliation]'
                        description: 'Affiliation options for proposals returned from the connection.'
                    includeUnpublished:
                        type: 'Boolean'
                        description: '(ROLE_SUPER_ADMIN only) Select also unpublished proposals.'
                        defaultValue: false
                    progressStatus:
                        type: 'ProposalProgressState'
                        description: 'The global progress status of the proposal.'
                    analysts:
                        description: "The analysts's ids assigned to the proposal"
                        type: '[ID!]'
                    supervisor:
                        description: "The supervisor's id assigned to the proposal"
                        type: 'ID'
                    decisionMaker:
                        description: "The decision-maker's id assigned to the proposal"
                        type: 'ID'
                    orderBy:
                        type: '[InternalProposalOrder]'
                        description: 'Ordering options for proposals returned from the connection.'
                        defaultValue: [ { field: 'PUBLISHED_AT', direction: 'ASC' } ]
                    excludeViewerVotes:
                        type: 'Boolean'
                        defaultValue: false
                    geoBoundingBox:
                        type: 'GeoBoundingBox'
                        description: 'Filter proposals by a given geo bounding box'
            viewerProposalsUnpublished:
                access: "@=hasRole('ROLE_USER')"
                type: 'InternalProposalConnection'
                argsBuilder: 'Relay::ForwardConnection'
                description: 'The viewer unpublished proposals (only visible by viewer).'
