LastnameRequirement:
    type: object
    inherits:
        - Node
        - Requirement
    config:
        interfaces:
            - Node
            - Requirement
        description: 'Requires a lastname'
        fields:
            viewerValue:
                type: 'String'
                access: "@=hasRole('ROLE_USER')"
                resolve: '@=resolver("Capco\\AppBundle\\GraphQL\\Resolver\\Requirement\\RequirementViewerValueResolver", [value, getUser()])'
                description: 'The lastname of the viewer.'
            participantValue:
                type: 'String'
                args:
                    token:
                        type: 'String!'
                        description: 'The token associated to the Participant.'
                resolve: '@=resolver("Capco\\AppBundle\\GraphQL\\Resolver\\Requirement\\RequirementParticipantValueResolver", [value, args])'
                description: 'The lastname of the participant.'
