UserOrNotRegistered:
    type: union
    config:
        types: [InternalUser, NotRegistered]
        description: User and NotRegistered
        resolveType: '@=resolver("Capco\\AppBundle\\GraphQL\\Resolver\\EventParticipant\\EventParticipantTypeResolver", [value])'
