DeleteOrganizationErrorCode:
    type: enum
    config:
        name: DeleteOrganizationErrorCode
        description: 'Available errors for an `deleteOrganization` mutation.'
        values:
            ORGANIZATION_NOT_FOUND:
                value: !php/const Capco\AppBundle\GraphQL\Mutation\Organization\DeleteOrganizationMutation::ORGANIZATION_NOT_FOUND
                description: 'No `Organization` match your `organizationId`.'
            ORGANIZATION_ALREADY_ANONYMIZED:
                value: !php/const Capco\AppBundle\GraphQL\Mutation\Organization\DeleteOrganizationMutation::ORGANIZATION_ALREADY_ANONYMIZED
                description: 'The given organization has already been anonymized.'
