InviteOrganizationMemberErrorCode:
    type: enum
    config:
        name: InviteOrganizationMemberErrorCode
        description: 'Available errors for an `inviteOrganizationMember` mutation.'
        values:
            ORGANIZATION_NOT_FOUND:
                value: !php/const Capco\AppBundle\GraphQL\Mutation\Organization\InviteOrganizationMemberMutation::ORGANIZATION_NOT_FOUND
                description: 'No `Organization` match your `organizationId`.'
            USER_ALREADY_MEMBER:
                value: !php/const Capco\AppBundle\GraphQL\Mutation\Organization\InviteOrganizationMemberMutation::USER_ALREADY_MEMBER
                description: 'The invited user is already a member of the organization.'
            USER_ALREADY_INVITED:
                value: !php/const Capco\AppBundle\GraphQL\Mutation\Organization\InviteOrganizationMemberMutation::USER_ALREADY_INVITED
                description: 'The invited user is already invited.'
            USER_NOT_ONLY_ROLE_USER:
                value: !php/const Capco\AppBundle\GraphQL\Mutation\Organization\InviteOrganizationMemberMutation::USER_NOT_ONLY_ROLE_USER
                description: 'The invited user is not only regular user.'
            USER_ALREADY_MEMBER_OF_ANOTHER_ORGANIZATION:
                value: !php/const Capco\AppBundle\GraphQL\Mutation\Organization\InviteOrganizationMemberMutation::USER_ALREADY_MEMBER_OF_ANOTHER_ORGANIZATION
                description: 'The invited user is already member of another organization.'
