OrganizationMemberRole:
    type: enum
    config:
        description: 'Available roles for organization member'
        values:
            ADMIN:
                value: !php/const Capco\AppBundle\Enum\OrganizationMemberRoleType::ADMIN
                description: 'Admin of the organization'
            USER:
                value: !php/const Capco\AppBundle\Enum\OrganizationMemberRoleType::USER
                description: 'Member of the organization.'
