Capco\AppBundle\Entity\Consultation:
    attributes:
        id:
            groups:
                [
                    Elasticsearch,
                    ElasticsearchNestedConsultation,
                    ElasticsearchOpinionNestedConsultation,
                    ElasticsearchVersionNestedConsultation,
                    ElasticsearchVoteNestedConsultation,
                    ElasticsearchArgumentNestedConsultation,
                    ElasticsearchSourceNestedConsultation,
                ]
        getOwner:
            serialized_name: owner
            groups:
              [
                  Elasticsearch
              ]
        elasticsearchTypeName:
            serialized_name: objectType
            groups: [Elasticsearch]
