Capco\AppBundle\Entity\Event:
    attributes:
        id:
            groups: [Events, ElasticsearchEvent]
        title:
            groups: [Events, ElasticsearchEvent]
        body:
            groups: [Events, ElasticsearchEvent]
        author:
            groups: [Events, ElasticsearchEventNestedAuthor]
        projects:
            groups: [ElasticsearchEventNestedProject]
        themes:
            groups: [ElasticsearchEventNestedTheme]
        getDistricts:
            serialized_name: districts
            groups: [ElasticsearchEvent, Events]
        canContribute:
            groups: [Events]
        createdAt:
            groups: [Events, ElasticsearchEvent]
        updatedAt:
            groups: [Events]
        startAt:
            groups: [Default, ElasticsearchEvent]
        endAt:
            groups: [Default, ElasticsearchEvent]
        media:
            groups: [Default]
        comments:
            groups: [Events]
        isEnabled:
            serialized_name: enabled
            groups: [Events, ElasticsearchEvent]
        address:
            groups: [ElasticsearchEvent]
        link:
            groups: [Events]
        translations:
            groups: [Events, ElasticsearchEvent]
        elasticsearchTypeName:
            serialized_name: objectType
            groups: [ElasticsearchEvent]
        owner:
            groups: [Events, ElasticsearchEvent]
        getStatus:
            serialized_name: eventStatus
            groups: [Events, ElasticsearchEvent]
