Capco\AppBundle\Entity\Opinion:
    attributes:
        id:
            groups:
                [
                    Opinions,
                    OpinionVersions,
                    ElasticsearchVersion,
                    OpinionLinkPreviews,
                    ElasticsearchOpinion,
                    ElasticsearchVoteNestedOpinion,
                    ElasticsearchArgumentNestedOpinion,
                    ElasticsearchSourceNestedOpinion,
                    ElasticsearchFollowerNestedOpinion,
                ]
        title:
            groups: [Opinions, OpinionVersions, OpinionLinkPreviews, ElasticsearchOpinion]
        body:
            groups: [Opinions, OpinionVersions, ElasticsearchOpinion]
        OpinionType:
            serialized_name: type
            groups:
                [
                    Opinions,
                    OpinionVersions,
                    OpinionVersionPreviews,
                    OpinionLinkPreviews,
                    ElasticsearchOpinionNestedOpinionType,
                ]
        published:
            groups:
                [
                    Opinions,
                    ElasticsearchOpinion,
                    ElasticsearchVoteNestedOpinion,
                    ElasticsearchArgumentNestedOpinion,
                    ElasticsearchSourceNestedOpinion,
                ]
        pinned:
            groups: [Opinions, ElasticsearchOpinion]
        consultation:
            groups: [ElasticSearch, Opinions, ElasticsearchOpinionNestedConsultation]
        publishedAt:
            groups:
                [
                    Opinions,
                    ElasticsearchOpinion,
                    ElasticsearchArgumentNestedOpinion,
                    ElasticsearchVoteNestedOpinion,
                ]
        trashedAt:
            groups:
                [
                    Opinions,
                    ElasticsearchOpinion,
                    ElasticsearchArgumentNestedOpinion,
                    ElasticsearchSourceNestedOpinion,
                ]
        position:
            groups: [Opinions, ElasticsearchOpinion]
        createdAt:
            groups: [Opinions, OpinionLinkPreviews, ElasticsearchOpinion]
        updatedAt:
            groups: [Opinions, OpinionLinkPreviews, ElasticsearchOpinion]
        appendices:
            groups: [Opinions, OpinionVersions]
        # votes:
        #   groups: [Opinions]
        # arguments:
        #   groups: [Opinions]
        modals:
            groups: [Opinions, OpinionVersions]
        sources:
            groups: [Opinions]
        author:
            groups: [Opinions, UserMedias, OpinionLinkPreviews, ElasticsearchOpinionNestedAuthor]
        answer:
            groups: [Opinions]
        ranking:
            groups: [Opinions]
        canContribute:
            serialized_name: isContribuable
            groups: [Opinions, OpinionVersions]
        getStep:
            type: object
            serialized_name: step
            groups: [Opinions, ElasticsearchOpinionNestedStep]
        getProject:
            type: object
            serialized_name: project
            groups: [ElasticsearchOpinionNestedProject]
        elasticsearchTypeName:
            serialized_name: objectType
            groups: [ElasticsearchOpinion]
