Capco\AppBundle\Entity\Proposal:
    exclusion_policy: ALL
    attributes:
        id:
            groups:
                [
                    Proposals,
                    ElasticsearchProposal,
                    ElasticsearchNestedProposal,
                    ElasticsearchVoteNestedProposal,
                ]
        getSelectionVotes:
            serialized_name: selection_votes
            groups: [ElasticsearchProposal]
        title:
            serialized_name: proposalTitle
            groups: [Proposals, ElasticsearchProposal]
        summary:
            groups: [Proposals, ElasticsearchProposal]
        body:
            serialized_name: proposalBody
            groups: [Proposals, ElasticsearchProposal]
        author:
            groups: [Proposals, ElasticsearchProposal]
        canContribute:
            groups: [Proposals]
        createdAt:
            groups: [Proposals, ElasticsearchProposal]
        updatedAt:
            groups: [Proposals, ElasticsearchProposal]
        publishedAt:
            groups: [ElasticsearchProposal]
        theme:
            groups: [Proposals, ElasticsearchProposalNestedTheme]
        district:
            groups: [Proposals, ElasticsearchProposalNestedDistrict]
        status:
            groups: [Proposals, ElasticsearchProposal]
        category:
            groups: [Proposals, ElasticsearchProposal]
        estimation:
            groups: [Proposals, ElasticsearchProposal]
        comments:
            groups: [Proposals]
        isDraft:
            groups: [Proposals, ElasticsearchProposal]
            serialized_name: draft
        proposalForm:
            groups: [Proposals, ElasticsearchProposal]
        progressSteps:
            groups: [Proposals]
        getSelectionsArray:
            serialized_name: selections
            groups: [Proposals, Statuses, ElasticsearchProposal]
        likers:
            groups: [Proposals]
        getFiledAddress:
            serialized_name: address
            groups: [Proposals, ElasticsearchProposal]
        isVisible:
            groups:
                [
                    PrivateProposals,
                    ElasticsearchProposal,
                    ElasticsearchCommentNestedProposal,
                    ElasticsearchVoteNestedProposal,
                ]
            serialized_name: visible
        getSummaryOrBodyExcerpt:
            groups: [Proposals]
            serialized_name: summaryOrBodyExcerpt
        getFullReference:
            groups: [Proposals, ElasticsearchProposal]
            serialized_name: reference
        isTrashed:
            serialized_name: trashed
            groups: [Proposals, ElasticsearchProposal]
        step:
            groups: [ElasticsearchProposalNestedStep]
        project:
            groups: [ElasticsearchCommentNestedProposal, ElasticsearchProposalNestedProject]
        published:
            groups: [ElasticsearchProposal]
        getProposalAnalystsArray:
            serialized_name: proposalAnalysts
            groups: [ElasticsearchProposal]
        supervisor:
            groups: [ElasticsearchProposal]
        decisionMaker:
            groups: [ElasticsearchProposal]
        getAnalysesArray:
            serialized_name: analyses
            groups: [ElasticsearchProposal]
        assessment:
            groups: [ElasticsearchProposal]
        decision:
            groups: [ElasticsearchProposal]
        getRevisionsArray:
            serialized_name: revisions
            groups: [ElasticsearchProposal]
        elasticsearchTypeName:
            serialized_name: objectType
            groups: [ElasticsearchProposal]
        getLocation:
            serialized_name: location
            groups: [ElasticsearchProposal]
        isArchived:
            serialized_name: archived
            groups: [ElasticsearchProposal]
