Capco\AppBundle\Entity\ProposalStatistics:
    attributes:
        getNbrOfMessagesSentToAuthor:
            groups: 
                [
                    Proposals,
                    ElasticsearchProposalStatistics,
                ]
            serialized_name: nbrOfMessagesSentToAuthor
