Capco\AppBundle\Entity\ProposalCategory:
    attributes:
        id:
            groups:
                [ProposalForms, ProposalCategories, Proposals, Elasticsearch, ElasticsearchProposal]
        name:
            groups: [ProposalForms, ProposalCategories, Proposals, ElasticsearchProposal]
