PreviewProposalOrderField:
    type: enum
    config:
        name: ProposalOrderField
        description: 'Properties by which proposal connections can be ordered.'
        values:
            COMMENTS:
                value: !php/const Capco\AppBundle\Enum\ProposalOrderField::COMMENTS
                description: 'Allows ordering a list of proposals by the number of comments it have.'
            COST:
                value: !php/const Capco\AppBundle\Enum\ProposalOrderField::COST
                description: 'Allows ordering a list of proposals by the cost it have been estimated.'
            CREATED_AT:
                value: !php/const Capco\AppBundle\Enum\ProposalOrderField::CREATED_AT
                description: 'Allows ordering a list of proposals by their creation date.'
            PUBLISHED_AT:
                value: !php/const Capco\AppBundle\Enum\ProposalOrderField::PUBLISHED_AT
                description: 'Allows ordering a list of proposals by when they were published.'
            RANDOM:
                value: !php/const Capco\AppBundle\Enum\ProposalOrderField::RANDOM
                description: 'Allows randomizing a list of proposals.'
            VOTES:
                value: !php/const Capco\AppBundle\Enum\ProposalOrderField::VOTES
                description: 'Allows ordering a list of proposals by the number of votes it have.'
            POINTS:
                value: !php/const Capco\AppBundle\Enum\ProposalOrderField::POINTS
                description: 'Allows ordering a list of proposals by the number of points it have.'
            NUMBER_OF_MESSAGES_RECEIVED:
                value: !php/const Capco\AppBundle\Enum\ProposalOrderField::NUMBER_OF_MESSAGES_RECEIVED
                description: 'Allows ordering a list of proposals by the number of messages it have received.'
