PreviewProposalVoteOrderField:
    type: enum
    config:
        name: ProposalVoteOrderField
        description: 'Ordering options for votes returned from the connection.'
        values:
            PUBLISHED_AT:
                value: !php/const Capco\AppBundle\Enum\VoteOrderField::PUBLISHED_AT
                description: 'Allows ordering a list of vote by when they were published.'
