PreviewStepState:
    type: enum
    config:
        name: StepState
        description: 'The possible states in which a step can be.'
        values:
            FUTURE:
                value: !php/const Capco\AppBundle\Enum\StepState::FUTURE
                description: 'The step has not started yet.'
            OPENED:
                value: !php/const Capco\AppBundle\Enum\StepState::OPENED
                description: 'The step is currently open.'
            CLOSED:
                value: !php/const Capco\AppBundle\Enum\StepState::CLOSED
                description: 'The step has been closed.'
