ProposalAnalysisState:
    type: enum
    config:
        description: 'The possible states for a proposal analysis.'
        values:
            IN_PROGRESS:
                value: !php/const Capco\AppBundle\Enum\ProposalStatementState::IN_PROGRESS
                description: "The proposal's analysis is currently being edited"
            FAVOURABLE:
                value: !php/const Capco\AppBundle\Enum\ProposalStatementState::FAVOURABLE
                description: "The proposal's related analysis state is favourable."
            UNFAVOURABLE:
                value: !php/const Capco\AppBundle\Enum\ProposalStatementState::UNFAVOURABLE
                description: "The proposal's related analysis state is unfavourable."
            TOO_LATE:
                value: !php/const Capco\AppBundle\Enum\ProposalStatementState::TOO_LATE
                description: "The proposal's related analysis has been not made in time."
            NONE:
                value: !php/const Capco\AppBundle\Enum\ProposalStatementState::NONE
                description: 'The analysis has not begun.'
