ProposalStepStatusColor:
    type: enum
    config:
        description: 'Different status type'
        values:
            INFO:
                description: 'Info color.'
                value: !php/const Capco\AppBundle\Enum\StatusColor::INFO
            PRIMARY:
                description: 'Primary color.'
                value: !php/const Capco\AppBundle\Enum\StatusColor::PRIMARY
            SUCCESS:
                description: 'Success color.'
                value: !php/const Capco\AppBundle\Enum\StatusColor::SUCCESS
            WARNING:
                description: 'Warning color.'
                value: !php/const Capco\AppBundle\Enum\StatusColor::WARNING
            CAUTION:
                description: 'Caution color.'
                value: !php/const Capco\AppBundle\Enum\StatusColor::CAUTION
            DANGER:
                description: 'Danger color.'
                value: !php/const Capco\AppBundle\Enum\StatusColor::DANGER
            DEFAULT:
                description: 'Default color.'
                value: !php/const Capco\AppBundle\Enum\StatusColor::NORMAL
