EmailingCampaignOrder:
    type: input-object
    config:
        description: 'Ways in which lists of campaigns can be ordered upon return.'
        fields:
            field:
                type: 'EmailingCampaignOrderField!'
                defaultValue: !php/const Capco\AppBundle\Enum\EmailingCampaignOrderField::SEND_AT
                description: The field to order users by.
            direction:
                type: 'OrderDirection!'
                defaultValue: !php/const Capco\AppBundle\Enum\OrderDirection::DESC
                description: The ordering direction.
