InternalProjectOwnerProjectOrder:
    type: input-object
    config:
        name: ProjectOwnerProjectOrder
        description: 'Ways in which project in admin list can be ordered.'
        fields:
            direction:
                type: 'OrderDirection!'
                description: 'The direction in which to order nodes.'
                defaultValue: 'DESC'
            field:
                type: 'InternalProjectOwnerProjectOrderField!'
                description: 'The field in which to order nodes by.'
                defaultValue: !php/const Capco\AppBundle\Enum\ProjectOrderField::PUBLISHED_AT
