LogicJumpInputNew:
    type: input-object
    config:
        fields:
            id:
                type: 'ID'
            always:
                type: 'Boolean'
            destination:
                type: 'ID!'
                description: 'The id of the question where the logic jump end if the conditions are fulfilled'
            conditions:
                type: '[LogicJumpConditionInput!]!'
                description: 'A collection of conditions that you have to fulfill for displaying the destination question'