PostOrder:
    type: input-object
    config:
        description: 'Ways in which lists of posts can be ordered upon return.'
        fields:
            field:
                type: 'PostOrderField!'
                defaultValue: !php/const Capco\AppBundle\Enum\PostOrderField::UPDATED_AT
                description: The field to order posts by.
            direction:
                type: 'OrderDirection!'
                defaultValue: !php/const Capco\AppBundle\Enum\OrderDirection::DESC
                description: The ordering direction.
