QuestionChoiceInput:
    type: input-object
    config:
        description: 'A possible choice of a question'
        fields:
            id:
                type: 'ID'
            title:
                type: 'String!'
            description:
                type: 'String'
            descriptionUsingJoditWysiwyg:
                type: 'Boolean'
            color:
                type: 'Color'
                description: 'The color assign with the question choice'
            image:
                type: 'ID'
            temporaryId:
                type: 'ID'
                description: 'Used to reference choice in logic jump.'
