QuestionInput:
    type: input-object
    config:
        fields:
            id:
                type: 'String'
                description: 'If null, a new question will be created.'
            alwaysJumpDestinationQuestion:
                type: 'ID'
            title:
                type: 'String!'
            type:
                type: 'QuestionTypeValue!'
            private:
                type: 'Boolean!'
                defaultValue: false
            required:
                type: 'Boolean!'
                defaultValue: false
            helpText:
                type: 'String'
            randomQuestionChoices:
                type: 'Boolean'
            otherAllowed:
                type: 'Boolean'
            validationRule:
                type: 'MultipleChoiceQuestionValidationRuleInput'
            choices:
                type: '[QuestionChoiceInput]'
            description:
                type: 'HTML'
            descriptionUsingJoditWysiwyg:
                type: 'Boolean'
            jumps:
                type: '[LogicJumpInput]'
            hidden:
                type: 'Boolean'
                defaultValue: false
            level:
                description: 'If not null, give the section s depth'
                type: 'Int'
            isRangeBetween:
                type: 'Boolean'
                description: 'can the viewer add a range (number question only)'
            rangeMin:
                type: 'Int'
                description: 'The minimal range (number question only)'
            rangeMax:
                type: 'Int'
                description: 'The maximal range (number question only)'
            groupedResponsesEnabled:
                type: 'Boolean'
                description: "Does the question have it's responses grouped"
            responseColorsDisabled:
                type: 'Boolean'
                description: 'Does the questions have disabled the responses colors'
            temporaryId:
                type: 'ID'
                description: 'Used to reference question in logic jump.'
