QuestionnaireOrder:
    type: input-object
    config:
        description: 'Ways in which lists of questionnaires can be ordered upon return.'
        fields:
            field:
                type: 'QuestionnaireOrderField!'
                defaultValue: !php/const Capco\AppBundle\Enum\QuestionnaireOrderField::CREATED_AT
                description: The field to order questionnaires by.
            direction:
                type: 'OrderDirection!'
                defaultValue: !php/const Capco\AppBundle\Enum\OrderDirection::DESC
                description: The ordering direction.
