InternalProposalDistrict:
    type: object
    inherits:
        - PreviewDistrict
    config:
        name: ProposalDistrict
        interfaces:
            - PreviewDistrict
            - Node
        description: 'A proposal district'
