QuestionJumpInput:
    type: input-object
    config:
        fields:
            questionId:
                type: 'ID!'
                description: 'The question ID.'
            alwaysJumpDestinationQuestion:
                type: 'ID'
                description: 'The question to display if no conditions are met.'
            jumps:
                type: '[LogicJumpInputNew]!'
                description: 'The logic jumps associated to the question.'

