AddDebateVoteErrorCode:
    type: enum
    config:
        name: AddDebateVoteErrorCode
        description: 'Available errors for an `addDebateVote` mutation.'
        values:
            UNKNOWN_DEBATE:
                value: !php/const Capco\AppBundle\GraphQL\Mutation\Debate\AddDebateVoteMutation::UNKNOWN_DEBATE
                description: 'No `Debate` match your `debateId`.'
            CLOSED_DEBATE:
                value: !php/const Capco\AppBundle\GraphQL\Mutation\Debate\AddDebateVoteMutation::CLOSED_DEBATE
                description: 'The debate is closed and be voted.'
