CreateDebateAnonymousArgumentErrorCode:
    type: enum
    config:
        name: CreateDebateAnonymousArgumentErrorCode
        description: 'Available errors for a `createDebateAnonymousArgument` mutation.'
        values:
            UNKNOWN_DEBATE:
                value: !php/const Capco\AppBundle\GraphQL\Mutation\Debate\CreateDebateArgumentMutation::UNKNOWN_DEBATE
                description: 'No `Debate` match your id.'
            ALREADY_HAS_ARGUMENT:
                value: !php/const Capco\AppBundle\GraphQL\Mutation\Debate\CreateDebateArgumentMutation::ALREADY_HAS_ARGUMENT
                description: 'There already is an argument with that email.'
