DebateVoteOrderField:
    type: enum
    config:
        description: 'Ordering options for votes returned from the connection.'
        values:
            PUBLISHED_AT:
                value: !php/const Capco\AppBundle\Enum\VoteOrderField::PUBLISHED_AT
            CREATED_AT:
                value: !php/const Capco\AppBundle\Enum\VoteOrderField::CREATED_AT
