DebateType:
    type: enum
    config:
        name: DebateType
        description: ''
        values:
            WYSIWYG:
                description: add a wysiwyg to allow the author to add additional content to the debate
                value: !php/const Capco\AppBundle\Enum\DebateType::WYSIWYG
            FACE_TO_FACE:
                description: remove the wysiwyg to only let the face to face debate
                value: !php/const Capco\AppBundle\Enum\DebateType::FACE_TO_FACE
