DebateArgumentOrderField:
    type: enum
    config:
        description: 'Ordering options for arguments returned from the connection.'
        values:
            PUBLISHED_AT:
                value: !php/const Capco\AppBundle\GraphQL\Resolver\Debate\DebateArgumentsResolver::ORDER_PUBLISHED_AT
            VOTE_COUNT:
                value: !php/const Capco\AppBundle\GraphQL\Resolver\Debate\DebateArgumentsResolver::ORDER_VOTE_COUNT
