DebateArgumentVoteOrderField:
    type: enum
    config:
        description: 'Ordering options for votes returned from the connection.'
        values:
            PUBLISHED_AT:
                value: !php/const Capco\AppBundle\GraphQL\Resolver\Debate\DebateArgumentVotesResolver::ORDER_PUBLISHED_AT
