AddAnonymousReplyPayload:
    type: relay-mutation-payload
    config:
        fields:
            reply:
                type: 'InternalAnonymousReply'
                description: 'The created reply'
            questionnaire:
                type: 'InternalQuestionnaire'
                description: 'The associated questionnaire'
            token:
                type: 'String'
                description: 'The reply token'
            errorCode:
                type: 'AddAnonymousReplyErrorCode'
                description: 'An error'
