AddMediatorsPayload:
    type: relay-mutation-payload
    config:
        fields:
            mediators:
                type: 'MediatorConnection!'
            step:
                type: 'InternalStep!'
