CreateOrUpdateConsultationInput:
    type: relay-mutation-input
    config:
        fields:
            consultations:
                type: '[ConsultationInput]!'
                description: 'List of consultations to create or update.'
            stepId:
                type: 'ID'
                description: 'If given determines if the consultations should be edited or copied'
