DeleteAccountInput:
    type: relay-mutation-input
    config:
        description: ''
        fields:
            type:
                type: 'DeleteAccountType!'
                description: 'You must chose a strategy to delete your account'
            userId:
                type: 'ID'
                description: 'The user to delete'
