DeleteStepInput:
    type: relay-mutation-input
    config:
        fields:
            stepId:
                type: 'ID!'
                description: 'The step ID to delete.'
            deleteRelatedResource:
                type: 'Boolean!'
                defaultValue: false
                description: 'If true also delete the related proposal form/questionnaire/consultation'

