DeleteAccountType:
    type: enum
    config:
        description: 'Differents strategies to delete an account'
        values:
            SOFT:
                value: !php/const Capco\AppBundle\Enum\DeleteAccountType::SOFT
                description: 'Anonymize the user and delete his content only on active steps'
            HARD:
                value: !php/const Capco\AppBundle\Enum\DeleteAccountType::HARD
                description: 'Anonymize the user and delete his content'
