InternalAddEventInput:
    type: relay-mutation-input
    inherits:
        - PreviewAddEventInput
    config:
        name: AddEventInput
        description: 'Input type of addEvent.'
        fields:
            enabled:
                type: 'Boolean'
                defaultValue: true
                description: 'Whether or not this event is published.'
            media:
                type: 'ID'
                description: 'The media to illustrate the event.'
            commentable:
                type: 'Boolean'
                defaultValue: true
                description: 'Whether or not this event is commentable.'
            # TODO rename to googleMapsAddress ?
            addressJson:
                type: 'String'
                description: 'The contents of the event addressJson.'
            customCode:
                type: 'String'
                description: 'The contents of the event customCode.'
            # cannot add access in type: relay-mutation-input
            projects:
                type: '[ID]'
                description: 'An array of Node IDs of projects associated to this event.'
            themes:
                type: '[ID]'
                description: 'An array of Node IDs of themes associated to this event.'
            guestListEnabled:
                type: 'Boolean!'
                defaultValue: false
                description: 'Whether or not this event is allow registrations.'
            author:
                type: 'ID'
                description: 'The Node ID of the author for this event.'
            translations:
                type: '[InternalEventTranslationInput!]!'
            bodyUsingJoditWysiwyg:
                description: 'Is the body using Jodit Wysiwyg.'
                type: 'Boolean'
            authorAgreeToUsePersonalDataForEventOnly:
                type: 'Boolean'
                description: 'Author of event agree to use personal data for event only'
            adminAuthorizeDataTransfer:
                type: 'Boolean'
                description: 'Admin authorize data transfer'
            steps:
                type: '[ID!]'
                description: 'An array of Node IDs of steps associated to this event.'
            measurable:
                type: 'Boolean!'
                defaultValue: false
                description: 'Whether or not this event is registrations measurable.'
            maxRegistrations:
                type: 'Int'
                description: 'If measurable what is the max allowed registrations'
            owner:
                type: 'ID'
                description: 'ID of the owner of the event, user or organization. If null, fallback on the viewer.'
            districts:
                type: '[ID]'
                description: 'An array of Node IDs of districts associated to this event.'
