InternalAddEventsPayload:
    type: relay-mutation-payload
    config:
        name: AddEventsPayload
        fields:
            importedEvents:
                type: '[InternalEvent!]!'
                description: 'List of imported events.'
            notFoundEmails:
                type: '[Email]!'
                description: "List of emails that didn't match an existing user."
            notFoundThemes:
                type: '[ID]!'
                description: "List of themes ID that didn't match an existing themes."
            notFoundProjects:
                type: '[ID]!'
                description: "List of projects ID that didn't match an existing projects."
            notFoundDistricts:
                type: '[ID]!'
                description: "List of districts ID that didn't match an existing districts."
            brokenDates:
                type: '[String]!'
                description: "List of dates that didn't got the good format"
