UpdateSelectionStepPayload:
    type: relay-mutation-payload
    config:
        fields:
            selectionStep:
                type: 'InternalSelectionStep!'
                description: 'The updated step.'