UpdateCollectStepPayload:
    type: relay-mutation-payload
    config:
        fields:
            collectStep:
                type: 'InternalCollectStep!'
                description: 'The updated step.'