UpdateParticipantRequirementPayload:
  type: relay-mutation-payload
  config:
    description: 'Payload type of UpdateParticipantRequirement.'
    fields:
      participant:
        type: 'InternalParticipant'
      requirement:
        type: 'Requirement'