PreviewGoogleMapsAddressType:
    type: enum
    config:
        name: GoogleMapsAddressType
        description: 'A list of possible types for a given address from Google Maps.'
        values:
            APPROXIMATE:
                value: !php/const Capco\AppBundle\Enum\GoogleMapsAddressType::APPROXIMATE
                description: 'Returns only the addresses that are characterized as approximate'
            GEOMETRIC_CENTER:
                value: !php/const Capco\AppBundle\Enum\GoogleMapsAddressType::GEOMETRIC_CENTER
                description: 'Returns only geometric centers of a location such as a polyline (for example, a street) or polygon (region).'
            RANGE_INTERPOLATED:
                value: !php/const Capco\AppBundle\Enum\GoogleMapsAddressType::RANGE_INTERPOLATED
                description: 'Returns only the addresses that reflect an approximation (usually on a road) interpolated between two precise points (such as intersections). An interpolated range generally indicates that rooftop geocodes are unavailable for a street address.'
            ROOFTOP:
                value: !php/const Capco\AppBundle\Enum\GoogleMapsAddressType::ROOFTOP
                description: 'Returns only the addresses for which Google has location information accurate down to street address precision.'
