StepAdminUrlOperationType:
    type: enum
    config:
        values:
            CREATE:
                value: !php/const Capco\AppBundle\Enum\StepAdminUrlOperationType::CREATE
            EDIT:
                value: !php/const Capco\AppBundle\Enum\StepAdminUrlOperationType::EDIT
