StepAdminUrlOperationType:
    type: enum
    config:
        values:
            CREATE:
                value: '@=constant("Capco\\AppBundle\\Enum\\StepAdminUrlOperationType::CREATE")'
            EDIT:
                value: '@=constant("Capco\\AppBundle\\Enum\\StepAdminUrlOperationType::EDIT")'
